"""Cost/benefit audit for the regional buildings (flavor guide R21-R27).
Compares every stat of every regular building level with the vanilla medians for the same level and checks the cost curve.
Rule: headline stats within 1.0x-1.5x of vanilla (the pack is a little stronger), cost exactly on the vanilla curve,
at least 4 distinct effects. Writes docs/BUILDING_AUDIT.md and exits non-zero if a rule is broken.
"""
import re
import sys
import os
import bld_data as B

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
VANILLA = {   # median of the regular buildings that have the field, levels I-IV (docs/VANILLA_BUILDING_CATALOG.md section 3)
    "monthly_income": [0.35, 0.55, 0.75, 0.95],
    "development_growth_factor": [0.045, 0.09, 0.12, 0.155],
    "county_opinion_add": [3, 6, 9, 12],
    "monthly_county_control_growth_add": [0.1, 0.2, 0.3, 0.4],
    "defender_holding_advantage": [2, 4, 6, 8],
    "monthly_piety": [0.1, 0.2, 0.3, 0.4],
    "monthly_prestige": [0.1, 0.2, 0.195, 0.26],
    "knight_effectiveness_mult": [0.02, 0.04, 0.06, 0.08],
    "levy": [100, 175, 175, 225],
    "max_garrison": [150, 300, 450, 800],
}
EXACT = {"fort_level"}          # integer stats: must equal vanilla
FEUDAL_COST = [150, 250, 340, 500]
TRIBAL_GOLD = [75, 100]
TRIBAL_PRESTIGE = [200, 350]


def blocks(text):
    out = {}
    for m in re.finditer(r"^(eir_[a-z0-9_]+) = \{", text, re.M):
        i, d = m.end(), 1
        while d:
            d += {"{": 1, "}": -1}.get(text[i], 0)
            i += 1
        out[m.group(1)] = text[m.end():i - 1]
    return out


def stats(body):
    out = {}
    for m in re.finditer(r"^\t+([a-z_]+) = (-?[0-9.]+)\s*$", body, re.M):
        out.setdefault(m.group(1), float(m.group(2)))
    return out


def main():
    text = open(os.path.join(ROOT, "common", "buildings", "eir_more_buildings.txt"), encoding="utf-8-sig").read()
    bl = blocks(text)
    report = ["# Regional building audit\n\nGenerated by `tools/audit_buildings.py`. Rule: headline stats 1.0x-1.5x of the vanilla median for the same level, "
              "cost on the vanilla curve (feudal 150/250/340/500 gold; tribal 75/100 gold + 200/350 prestige), at least 4 distinct effects.\n\n"
              "| Building | Cost | Effects | Worst ratio | Verdict |\n|---|---|---|---|---|\n"]
    bad = []
    n = 0
    for fam in B.FAMILIES:
        key = fam[0]
        for tribal in (True, False):
            levels = 2 if tribal else 4
            for lv in range(levels):
                k = "%s_t_%02d" % (key, lv + 1) if tribal else "%s_%02d" % (key, lv + 1)
                body = bl.get(k)
                if body is None:
                    bad.append("missing building " + k)
                    continue
                n += 1
                st = stats(body)
                gold = st.get("cost_gold")
                pres = st.get("cost_prestige")
                if tribal:
                    ok_cost = gold == TRIBAL_GOLD[lv] and pres == TRIBAL_PRESTIGE[lv]
                    cost = "%dg + %dp" % (gold, pres)
                else:
                    ok_cost = gold == FEUDAL_COST[lv] and pres is None
                    cost = "%dg" % gold
                ratios = []
                for f, vals in VANILLA.items():
                    if f in st:
                        ratios.append((st[f] / vals[lv], f))
                for f in EXACT:
                    if f in st and st[f] != lv + 1:
                        bad.append("%s fort_level %s != %d" % (k, st[f], lv + 1))
                effects = [f for f in st if f not in ("cost_gold", "cost_prestige", "construction_time")]
                worst = max(ratios)[0] if ratios else 1.0
                low = min(ratios)[0] if ratios else 1.0
                verdict = "ok"
                if not ok_cost:
                    verdict = "COST OFF CURVE"
                    bad.append(k + " cost")
                if len(effects) < 4:
                    verdict = "TOO FEW EFFECTS"
                    bad.append("%s only %d effects" % (k, len(effects)))
                if worst > 1.55 or low < 0.95:
                    verdict = "OFF VANILLA LINE (%.2f..%.2f)" % (low, worst)
                    bad.append("%s ratio %.2f..%.2f" % (k, low, worst))
                report.append("| %s | %s | %d | %.2f | %s |\n" % (k, cost, len(effects), worst, verdict))
    report.append("\n%d building levels audited; %d problems.\n" % (n, len(bad)))
    open(os.path.join(ROOT, "docs", "BUILDING_AUDIT.md"), "w", encoding="utf-8").write("".join(report))
    print("audited %d building levels, %d problems" % (n, len(bad)))
    for b in bad:
        print("  PROBLEM", b)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
