"""Update 2, part C: Britain, conquest, triumph, culture and the Insular Union (0480-0529).
Pulse-fired flavor events (0480-0499, 0516-0527) and the ceremonies of the new decisions (0500-0515)."""
from ev_h import *
import ev_h
EVENTS = ev_h.EVENTS = []

FILI = "has_global_variable = eir_done_fili"
BROTH = "has_global_variable = eir_done_brotherhood"
UNION = "has_global_variable = eir_done_union"
FOREIGN = "eir_has_foreign_britain_counties_trigger = yes"
CELTBR = "eir_has_celtic_britain_counties_trigger = yes"
BRIT_L = "is_ai = yes\nis_ruler = yes\nhighest_held_title_tier >= tier_county\nculture ?= { has_cultural_pillar = heritage_brythonic }\nNOT = { this = root }"
BRIT_ANY = "any_ruler = {\n" + BRIT_L.replace("\n", "\n\t").join(["\t", ""]) + "\n}"
PICK_BRIT = "random_ruler = {\n\tlimit = {\n" + BRIT_L.replace("\n", "\n\t\t").join(["\t\t", ""]) + "\n\t}\n\tsave_scope_as = eir_briton\n}"
BRIT_P = "left_portrait = {\n\tcharacter = scope:eir_briton\n\tanimation = personality_honorable\n}"
CONQ_COUNTY = "random_sub_realm_county = {\n\tlimit = { eir_foreign_conquest_county_trigger = yes }\n\tsave_scope_as = eir_conq_county\n}"

# =============================================================================
# PULSE-FIRED FLAVOR: the foreign lands you hold, and the Celtic neighbours
# =============================================================================
ev(480, "A Saxon Thegn Kneels",
   "A thegn of the conquered county has come to your hall, unarmed, and asked to speak.",
   "He is sixty, with a limp and a good hall and a daughter he is clearly worried about. He says the English of his county are tired of being fought over. He says that if the Gael will keep the law and protect the churches, he will answer for his neighbours. He asks nothing in return except that nobody burns the mill.",
   [
       O("Accept his oath and let him keep his land.",
         "add_character_modifier = { modifier = eir_two_peoples_modifier years = 8 }", PRESTIGE_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_saxon_moot_modifier years = 8 } }",
         "eir_resent_clear_effect = yes", st=S_FORGIVE, ai=40, ai_mod=[("forgiving", 20), ("just", 15)]),
       O("Take his daughter as a hostage, and his oath too.",
         "add_hook = { target = scope:eir_thegn type = strong_hook }", PRESTIGE_S, "scope:eir_conq_county ?= { change_county_control = minor_county_control_gain }", "add_character_modifier = { modifier = eir_hostage_peace_modifier years = 6 }",
         st=S_HARD, ai=25, ai_mod=[("callous", 15), ("paranoid", 15)]),
       O("Tell him the Gael do not make oaths with their conquered.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 6 } }", "change_variable = { name = eir_resent add = 1 }",
         st=S_ARROG, ai=15, ai_mod=[("arrogant", 20), ("sadistic", 10)]),
       O("Invite him to teach your poets the English law.",
         PRESTIGE_M, xp("lifestyle_poet", 15), "add_character_modifier = { modifier = eir_gaelic_court_modifier years = 6 }", "eir_resent_clear_effect = yes",
         gate="learning >= 9", st=S_HUMBLE, ai=30, ai_mod=[("humble", 15), ("gregarious", 10)]),
   ],
   "vassal", gate=FOREIGN, cooldown=12, immediate=CONQ_COUNTY + "\nrandom_vassal = {\n\tsave_scope_as = eir_thegn\n}\nif = {\n\tlimit = { NOT = { exists = scope:eir_thegn } }\n\tcreate_character = {\n\t\tlocation = root.capital_province\n\t\tage = { 45 62 }\n\t\tgender_female_chance = 0\n\t\tculture = scope:eir_conq_county.culture\n\t\tfaith = scope:eir_conq_county.faith\n\t\trandom_traits = yes\n\t\tsave_scope_as = eir_thegn\n\t}\n}",
   portraits="left_portrait = {\n\tcharacter = scope:eir_thegn\n\tanimation = personality_honorable\n}")

ev(481, "The Welsh Bard Comes to Court",
   "A bard out of Gwynedd has arrived with a harp, a satchel of manuscripts and a poem in three languages.",
   "He says he has walked from Anglesey, and that he has heard there are Irish poets who can recite the Táin from memory. He would like to hear it. He would, in exchange, recite the whole of Taliesin. The two traditions have been separated by a sea and a thousand years. They seem to understand each other perfectly.",
   [
       O("Host a night of poets, Irish and Welsh together.",
         PRESTIGE_M, xp("lifestyle_poet", 30), xp("lifestyle_reveler", 15), "add_character_modifier = { modifier = eir_bardic_circuit_modifier years = 6 }", "eir_court_opinion_effect = { MODIFIER = eir_poet_praise_opinion OPINION = 5 }",
         st=S_GEN, ai=45, ai_mod=[("gregarious", 15), ("generous", 10)]),
       O("Commission a poem that joins the two peoples.",
         PRESTIGE_S, "eir_legend_title_effect = { TITLE = primary_title }", "add_character_modifier = { modifier = eir_insular_song_modifier years = 10 }", GOLD_S,
         gate=FILI, st=S_HUMBLE, ai=35),
       O("Ask him to teach your children Welsh.",
         "add_character_modifier = { modifier = eir_welsh_tongue_modifier years = 12 }", PRESTIGE_S, "eir_court_opinion_effect = { MODIFIER = eir_poet_praise_opinion OPINION = 3 }",
         st=S_PATIENT, ai=30, ai_mod=[("patient", 15)]),
       O("Pay him, thank him, and send him on.",
         GOLD_S, STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", st=S_CONTENT, ai=20),
   ],
   "court", gate=BROTH, cooldown=15)

ev(482, "The Tale of Arthur",
   "A British poet recites the story of a king who sleeps under a hill and will return when Britain needs him.",
   "The poem is unfamiliar and also not. It has a king, a sword, a round table that is really a hall, and a betrayal on a field the poet will not name. He says it is a Welsh story, and a Cornish one, and a Breton one, and an English one, and that every people on the island will claim him.\n\nHe looks at you meaningfully.",
   [
       O("Say that the king was a Gael on his mother's side.",
         "add_character_modifier = { modifier = eir_insular_song_modifier years = 8 }", PRESTIGE_M, "eir_legend_title_effect = { TITLE = primary_title }", "add_character_modifier = { modifier = eir_false_pedigree_modifier years = 4 }",
         gate=BROTH, st=S_ARROG, ai=30, ai_mod=[("arrogant", 20), ("ambitious", 10)]),
       O("Ask him to teach the poem to your own poets.",
         PRESTIGE_S, xp("lifestyle_poet", 30), "add_character_modifier = { modifier = eir_bardic_circuit_modifier years = 6 }", gate=FILI,
         st=S_HUMBLE, ai=40, ai_mod=[("humble", 15)]),
       O("Commission a sword for the Gael to match the story.",
         GOLD_M, "eir_make_artifact_effect = { NAME = eir_hill_king_sword_name DESC = eir_hill_king_sword_desc TYPE = sword VISUALS = sword MODIFIER = eir_hill_king_sword_modifier }", PRESTIGE_S,
         gate="gold >= 150", st=S_AMBIT, ai=30),
       O("Enjoy the story, and say nothing of your own.",
         STRESS_DOWN, PRESTIGE_S, xp("lifestyle_reveler", 15), st=S_CONTENT, ai=35, ai_mod=[("content", 20)]),
   ],
   "legend", gate=CELTBR, cooldown=25)

ev(483, "The Cornish Tin Merchant",
   "A Cornish merchant has come with a cargo of tin and an unusual question.",
   "He is not asking to sell tin. He is asking where he can buy hides, wool and wolfhound pups at a fair price, and he is prepared to pay in the same tin you would otherwise buy from the Franks. He is Cornish; he has no love for the Saxons. He has noticed that the Irish do not have one either.",
   [
       O("Strike a trade agreement for the whole coast.",
         GAIN_M, "add_character_modifier = { modifier = eir_irish_sea_trade_modifier years = 6 }", PRESTIGE_S, xp("lifestyle_traveler", 15),
         gate="eir_ports_trigger = { N = 1 }", st=S_SHREWD, ai=40, ai_mod=[("shrewd", 15), ("greedy", 10)]),
       O("Give him a safe-conduct and a letter to the Welsh princes.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_hospitality_modifier years = 5 }", "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 3 }",
         st=S_GEN, ai=30, ai_mod=[("generous", 15)]),
       O("Charge a tin-toll at every Irish port.",
         GAIN_M, LOSS_S, STRESS_UP, st=S_GREED, ai=20, ai_mod=[("greedy", 20)]),
       O("Invest in a ship to Cornwall.",
         GOLD_M, luck("t483w", "The ship returns laden", "add_gold = medium_gold_value\nadd_prestige = minor_prestige_gain\nadd_trait_xp = { trait = lifestyle_traveler value = 25 }",
                      "t483l", "The ship is lost off the Scillies", "add_prestige = minor_prestige_loss", p=55),
         gate="gold >= 150\neir_ports_trigger = { N = 1 }", st=S_BRAVE, ai=25),
   ],
   "stewardship", gate="eir_ports_trigger = { N = 1 }\ncurrent_year >= 868", cooldown=20)

ev(484, "The Saint Crosses the Sea",
   "Monks from Saint David's have come with a gift: a fragment of the saint's staff, and a request.",
   "They want a copy of the Irish Rule, a loan of the Irish scribes and an introduction to the abbot of Clonmacnoise. They offer the staff, a relic with a long history, and an admission, in a murmur, that the Irish monks are better scribes. Wales and Ireland have been exchanging saints since the days of Patrick, and nobody is counting.",
   [
       O("Accept the staff and send them scribes.",
         PIETY_L, "add_character_modifier = { modifier = eir_missionary_glory_modifier years = 6 }", xp("lifestyle_mystic", 25), PRESTIGE_S,
         gate="piety >= 80", st=S_ZEAL, ai=40, ai_mod=[("zealous", 20)]),
       O("Accept the staff and keep the scribes at home.",
         PIETY_M, "eir_make_artifact_effect = { NAME = eir_david_staff_name DESC = eir_david_staff_desc TYPE = goblet VISUALS = goblet MODIFIER = eir_david_staff_modifier }",
         st=S_GREED, ai=30, ai_mod=[("greedy", 15)]),
       O("Offer a joint pilgrimage to Rome.",
         PIETY_M, PRESTIGE_M, xp("lifestyle_traveler", 25), "add_character_modifier = { modifier = eir_pilgrim_modifier years = 4 }",
         gate="piety >= 150", st=S_ZEAL, ai=20, ai_mod=[("zealous", 15), ("brave", 10)]),
       O("Thank them, and send them home with a fine book.",
         PIETY_S, PRESTIGE_S, "add_character_modifier = { modifier = eir_hospitality_modifier years = 4 }", st=S_GEN, ai=30),
   ],
   "faith", gate=CELTBR + "\npiety >= 60", cooldown=20)

ev(485, "The English Bishop Refuses",
   "An English bishop has locked his cathedral to the Irish monks you sent.",
   "He is not entirely unreasonable. The Irish monks keep their own Easter, wear their own tonsure and say Mass in a Latin the bishop describes as colourful. He does not want them preaching in his diocese. He has not, so far, said that he does not want you.",
   [
       O("Appeal to the Archbishop and the Pope.",
         PIETY_M, PRESTIGE_S, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 6 }", STRESS_UP,
         gate="piety >= 100", st=S_PATIENT, ai=35, ai_mod=[("patient", 15), ("zealous", 10)]),
       O("Have the monks adopt the Roman tonsure for the sake of peace.",
         PIETY_S, "add_character_modifier = { modifier = eir_easter_rift_modifier years = 5 }", "eir_resent_clear_effect = yes", PRESTIGE_S,
         st=S_FORGIVE, ai=30, ai_mod=[("humble", 15), ("forgiving", 10)]),
       O("Build your own church next door.",
         GOLD_M, PIETY_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 10 } }", PRESTIGE_S,
         gate="gold >= 120", st=S_AMBIT, ai=35, ai_mod=[("ambitious", 15)]),
       O("Take the cathedral by force and install your own abbot.",
         "add_dread = medium_dread_gain", "add_piety = medium_piety_loss", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 10 } }",
         "change_variable = { name = eir_resent add = 1 }", st=S_HARD, ai=10, ai_mod=[("wrathful", 20), ("callous", 10)]),
   ],
   "faith", gate=FOREIGN + "\npiety >= 60", cooldown=20, immediate=CONQ_COUNTY)

ev(486, "A British Prince in Exile",
   "A prince of the Britons has landed with thirty men and a carved gaming-board, asking for refuge.",
   "His uncle took the hall and the herds. He took the board, the one thing no one could take from him: an ivory board his grandfather played on, and that grandfather's grandfather before him. He says it is the last thing in Britain that still belongs to the old kings. He would like a roof, a sword and the loan of an army.",
   [
       O("Shelter him as a guest, and ask for nothing.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_hospitality_modifier years = 8 }", "scope:eir_briton = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }", xp("lifestyle_reveler", 15),
         st=S_GEN, ai=40, ai_mod=[("generous", 20), ("compassionate", 15)]),
       O("Shelter him, and press his claim through your own army.",
         "add_character_flag = { flag = eir_oath_to_reclaim years = 10 }", PRESTIGE_S, "add_hook = { target = scope:eir_briton type = strong_hook }", "add_character_modifier = { modifier = eir_kin_defended_modifier years = 6 }",
         gate="eir_stage1_trigger = yes", st=S_AMBIT, ai=30, ai_mod=[("ambitious", 20)]),
       O("Marry him to a daughter of your house.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 12 }", "add_hook = { target = scope:eir_briton type = strong_hook }",
         gate="any_child = { is_adult = yes is_female = yes is_married = no }", st=S_SHREWD, ai=30, ai_mod=[("shrewd", 15)]),
       O("Turn him away. It is not your quarrel.",
         STRESS_DOWN, "scope:eir_briton = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -15 } }", LOSS_S, st=S_CYN, ai=15, ai_mod=[("cynical", 15)]),
   ],
   "court", gate=BRIT_ANY + "\n" + BROTH, cooldown=20, immediate=PICK_BRIT, portraits=BRIT_P)

ev(487, "The Pictish Stone",
   "A farmer has dug up a carved stone with a symbol no living man can read.",
   "It shows a double disc and a Z-rod, a mirror and a comb, and a beast that might be a wolf or a salmon. The old men of the glen say the Picts put such stones up and nobody knows why. The Picts spoke a language that is not quite Welsh and not quite Irish. Nobody has written a word of it down.",
   [
       O("Set up the stone in your hall, as a memorial.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_pictish_memory_modifier years = 10 }", "eir_legend_title_effect = { TITLE = primary_title }",
         st=S_HUMBLE, ai=40, ai_mod=[("humble", 15)]),
       O("Send the stone to the scholars at Armagh to decode.",
         PRESTIGE_S, xp("lifestyle_poet", 20), "add_character_modifier = { modifier = eir_royal_ollamh_modifier years = 6 }", GOLD_S,
         gate="learning >= 8", st=S_PATIENT, ai=30),
       O("Sell it to a passing Frankish collector.",
         GAIN_M, "add_piety = minor_piety_loss", STRESS_DOWN, st=S_GREED, ai=20, ai_mod=[("greedy", 20)]),
       O("Break it up for the road.",
         GAIN_S, "add_prestige = minor_prestige_loss", "eir_trait_effect = { TRAIT = callous OPPOSITE = compassionate CHANCE = 15 }", st=S_CYN, ai=10, ai_mod=[("lazy", 15)]),
   ],
   "legend", gate=CELTBR + "\ncurrent_year >= 868", cooldown=30)

ev(488, "Hengist's Heirs",
   "An English thane in the conquered county has been quietly gathering his neighbours at night.",
   "They meet in a barn and drink to the old kings of Wessex. They are not planning a revolt, exactly. They are planning a funeral for a dead tongue and the burial of a tradition. But funerals are dangerous. Funerals have crowds. Crowds have knives.",
   [
       O("Attend the meeting in disguise.",
         luck("t488w", "You hear every word and learn who the leader is", "add_prestige = minor_prestige_gain\nadd_character_modifier = { modifier = eir_foreknowledge_modifier years = 4 }\nscope:eir_conq_county ?= { change_county_control = minor_county_control_gain }",
              "t488l", "You are recognised and have to fight your way out", "add_prestige = minor_prestige_loss\nincrease_wounds_effect = { REASON = fight }\nadd_stress = minor_stress_gain", p=50, bonus=(20, "intrigue >= 12")),
         gate="OR = {\nintrigue >= 10\nhas_trait = deceitful\nhas_trait = brave\n}", st=S_DECEIT, ai=25, ai_mod=[("deceitful", 15), ("brave", 10)]),
       O("Send a priest to preach at the funeral.",
         PIETY_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_saxon_moot_modifier years = 6 } }", "eir_resent_clear_effect = yes", PRESTIGE_S,
         st=S_ZEAL, ai=35, ai_mod=[("zealous", 15), ("patient", 10)]),
       O("Seize the thane and make an example.",
         "add_dread = medium_dread_gain", "scope:eir_conq_county ?= { change_county_control = medium_county_control_gain }", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 8 } }",
         "change_variable = { name = eir_resent add = 1 }", st=S_HARD, ai=20, ai_mod=[("sadistic", 20), ("callous", 15)]),
       O("Invite the thane to your table and ask what he wants.",
         PRESTIGE_M, "eir_trait_effect = { TRAIT = patient OPPOSITE = wrathful CHANCE = 25 }", "eir_resent_clear_effect = yes", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_saxon_moot_modifier years = 10 } }",
         gate="diplomacy >= 9", st=S_FORGIVE, ai=30, ai_mod=[("forgiving", 20), ("gregarious", 10)]),
   ],
   "intrigue", gate=FOREIGN + "\nhas_variable = eir_recelt", cooldown=12, immediate=CONQ_COUNTY)

ev(489, "The Settlers' Ship",
   "A ship has come in from Antrim carrying forty families with their cattle, asking for land.",
   "They are the younger sons and daughters of the Irish septs: the ones who will inherit nothing because they are third or fourth or tenth in line. They have heard that Britain is wide and the land is rich. They have not heard that Britain's farmers have views about this. They are brave, hungry and not terribly well informed.",
   [
       O("Settle them in the conquered county as free tenants.",
         "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_gaelic_settlers_modifier years = 12 } }", PRESTIGE_S, "change_variable = { name = eir_resent add = 1 }", GAIN_S,
         st=S_GEN, ai=40, ai_mod=[("generous", 15), ("ambitious", 10)]),
       O("Settle them near the monasteries, to learn the language.",
         PIETY_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 10 } }", PRESTIGE_S,
         st=S_PATIENT, ai=35, ai_mod=[("patient", 15), ("zealous", 10)]),
       O("Charge them a rent and keep them under watch.",
         GAIN_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_gaelic_settlers_modifier years = 6 } }", STRESS_UP,
         st=S_GREED, ai=30, ai_mod=[("greedy", 20)]),
       O("Send them home. Britain is not ready.",
         STRESS_DOWN, "add_prestige = minor_prestige_loss", st=S_CRAVEN, ai=10, ai_mod=[("craven", 15)]),
   ],
   "stewardship", gate=FOREIGN, cooldown=12, immediate=CONQ_COUNTY)

ev(490, "A Charter in Two Tongues",
   "A scribe has drawn up the first charter of your reign in Latin, Irish and the local English.",
   "It is a good charter, short and clear. It is also, in the English version, about a third longer than the Irish, because the English scribe keeps adding clauses that protect the thanes. The Irish scribe is complaining. The Latin scribe has taken no side, which is how he has survived this long.",
   [
       O("Seal the three versions as equal.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 8 }", "eir_resent_clear_effect = yes", xp("lifestyle_poet", 15),
         st=S_FORGIVE, ai=40, ai_mod=[("just", 20), ("humble", 10)]),
       O("Seal only the Irish, and let the others follow.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_gaelic_court_modifier years = 6 }", "change_variable = { name = eir_resent add = 1 }",
         st=S_ARROG, ai=20, ai_mod=[("arrogant", 15)]),
       O("Have the poets add a verse to the preamble.",
         PRESTIGE_S, xp("lifestyle_poet", 20), "add_character_modifier = { modifier = eir_bardic_circuit_modifier years = 4 }", gate=FILI,
         st=S_HUMBLE, ai=30),
       O("Order the scribes to keep their quarrels to themselves.",
         STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", st=S_HARD, ai=30, ai_mod=[("lazy", 10)]),
   ],
   "court", gate=FOREIGN, cooldown=15, immediate=CONQ_COUNTY)

ev(491, "The Wedding of Two Peoples",
   "A young Gael and a young Saxon girl have asked permission to be married in the same church.",
   "They are the son of your steward and the daughter of the reeve of the conquered county. They met at the market. They have been told by everyone that it is impossible. They would like your permission, mainly to prove everyone wrong. The wedding will be conducted in Irish and English, in alternate verses.",
   [
       O("Host the wedding in your own hall.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 8 }", xp("lifestyle_reveler", 25), "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_saxon_moot_modifier years = 8 } }",
         "eir_resent_clear_effect = yes", st=S_GEN, ai=45, ai_mod=[("gregarious", 20), ("compassionate", 10)]),
       O("Give them a cottage and your blessing.",
         PRESTIGE_S, "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 3 }", GOLD_S, STRESS_DOWN,
         st=S_KIND, ai=40, ai_mod=[("compassionate", 15)]),
       O("Forbid it. The peoples should stay apart.",
         PRESTIGE_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 5 } }", "change_variable = { name = eir_resent add = 1 }",
         st=S_HARD, ai=15, ai_mod=[("stubborn", 15), ("arrogant", 10)]),
       O("Marry your own heir to the girl's sister.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 12 }", "eir_resent_clear_effect = yes",
         gate="exists = primary_heir", st=S_SHREWD, ai=20, ai_mod=[("ambitious", 15)]),
   ],
   "marriage", gate=FOREIGN, cooldown=18, immediate=CONQ_COUNTY)

ev(492, "The Pilgrim Road to St Davids",
   "A caravan of Irish pilgrims has gone to Saint David's and not come back.",
   "There were sixty of them, with a monk and a guide. They left in April and they should have returned in June. A peddler says they were detained at a border. A fisherman says they were taken by Saxons. The monks of the pilgrimage say they should not have gone without an escort, and that they told you so.",
   [
       O("Send an escort to find them.",
         GOLD_S, luck("t492w", "The pilgrims are found alive and well", "add_piety = medium_piety_gain\nadd_prestige = minor_prestige_gain\nadd_trait_xp = { trait = lifestyle_traveler value = 20 }",
                      "t492l", "The pilgrims are found, but half have died", "add_piety = minor_piety_loss\nadd_stress = minor_stress_gain", p=60, bonus=(15, "martial >= 10")),
         st=S_BRAVE, ai=40, ai_mod=[("compassionate", 15), ("brave", 10)]),
       O("Pray for them and write to the Welsh bishop.",
         PIETY_S, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 4 }", xp("lifestyle_mystic", 15), st=S_ZEAL, ai=30, ai_mod=[("zealous", 15)]),
       O("Blame the Saxons and demand a blood-price.",
         PRESTIGE_S, "add_dread = minor_dread_gain", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 4 } }",
         gate=FOREIGN, st=S_WRATH, ai=20, ai_mod=[("wrathful", 20)]),
       O("Do nothing. They went at their own risk.",
         STRESS_DOWN, "add_piety = minor_piety_loss", st=S_HARD, ai=10),
   ],
   "travel", gate=CELTBR + "\npiety >= 60", cooldown=20, immediate=CONQ_COUNTY)

ev(493, "A Cumbrian Envoy",
   "An envoy of the Britons of the Clyde has arrived with an offer you did not expect.",
   "His king sits on a rock above the river, with a hall of Welsh-speaking Britons and a coast full of Norse. He is not unfriendly. He wants an alliance, a joint stand against whoever comes next, and a shared poet. He is also asking, with careful politeness, whether you intend to take his kingdom.",
   [
       O("Swear a pact of mutual defence.",
         "add_hook = { target = scope:eir_briton type = favor_hook }", PRESTIGE_M, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 10 }", "scope:eir_briton = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }",
         gate="diplomacy >= 9", st=S_HONEST, ai=45, ai_mod=[("honest", 15), ("gregarious", 10)]),
       O("Ask for a marriage instead.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 15 }", "add_hook = { target = scope:eir_briton type = strong_hook }",
         gate="any_child = { is_adult = yes is_married = no }", st=S_SHREWD, ai=30, ai_mod=[("shrewd", 15)]),
       O("Give an ambiguous answer and watch.",
         "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 3 }", STRESS_UP, PRESTIGE_S, st=S_DECEIT, ai=25, ai_mod=[("deceitful", 20), ("paranoid", 10)]),
       O("Tell him the Gael intend to take everything.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "scope:eir_briton = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -25 } }", "add_character_flag = { flag = eir_oath_to_reclaim years = 8 }",
         st=S_ARROG, ai=15, ai_mod=[("arrogant", 20), ("ambitious", 15)]),
   ],
   "diplomacy", gate=BRIT_ANY + "\n" + BROTH, cooldown=20, immediate=PICK_BRIT, portraits=BRIT_P)

ev(494, "The Sea-Road to Alba",
   "A shipmaster says the sea between Antrim and Kintyre can be crossed in a day, if the right harbours are kept.",
   "The crossing has been made for a thousand years by monks, raiders and cattle drovers, and no one has ever organised it. The shipmaster proposes two quays, a chain of beacons, a tax on every passenger and a licence for his friends. He has done the sums. They are quite good.",
   [
       O("Back the scheme with silver and a royal charter.",
         GOLD_M, "add_character_modifier = { modifier = eir_sea_road_modifier years = 12 }", PRESTIGE_S, "every_realm_county = {\n\tlimit = { is_coastal_county = yes }\n\tadd_county_modifier = { modifier = eir_beacon_county_modifier years = 10 }\n}",
         gate="gold >= 150\neir_ports_trigger = { N = 2 }", st=S_SHREWD, ai=40, ai_mod=[("diligent", 15), ("shrewd", 10)]),
       O("Take a share of the tolls and nothing else.",
         GAIN_M, "add_character_modifier = { modifier = eir_irish_sea_trade_modifier years = 5 }", STRESS_DOWN, st=S_GREED, ai=35, ai_mod=[("greedy", 20)]),
       O("Insist the monks run it as a charity.",
         PIETY_M, "add_character_modifier = { modifier = eir_pilgrim_modifier years = 8 }", PRESTIGE_S, st=S_ZEAL, ai=25, ai_mod=[("zealous", 20)]),
       O("Decline. The Norse would raid the quays.",
         STRESS_DOWN, "add_prestige = minor_prestige_loss", st=S_CRAVEN, ai=15, ai_mod=[("craven", 15), ("content", 10)]),
   ],
   "stewardship", gate="eir_ports_trigger = { N = 2 }\ncurrent_year >= 868", cooldown=25)

ev(495, "The Hedge-School Master",
   "A weary old schoolmaster has come to the conquered county with a sack of books and a boy.",
   "He teaches under hawthorns, in the open, because the Church does not pay him and the thane does not like him. His pupils learn the old tongue by repeating the same ten stories until they cry. He wants a roof for winter, a copy of the Táin and a promise that nobody will burn the hedge.",
   [
       O("Build him a schoolhouse and pay his wage.",
         GOLD_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 15 } }", PRESTIGE_S, xp("lifestyle_poet", 15),
         st=S_GEN, ai=40, ai_mod=[("generous", 15), ("zealous", 10)]),
       O("Give him a roof and let him teach as he likes.",
         "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 6 } }", PRESTIGE_S, STRESS_DOWN, st=S_PATIENT, ai=40, ai_mod=[("patient", 15)]),
       O("Ask him to write down the local legends in both languages.",
         PRESTIGE_M, "eir_legend_title_effect = { TITLE = primary_title }", xp("lifestyle_poet", 20), gate=FILI, st=S_HUMBLE, ai=30),
       O("Send him on. The county is not ready for schools.",
         STRESS_DOWN, "add_prestige = minor_prestige_loss", st=S_HARD, ai=15),
   ],
   "learning", gate=FOREIGN + "\nhas_variable = eir_recelt", cooldown=12, immediate=CONQ_COUNTY)

ev(496, "Names on the Land",
   "A surveyor has found three names for the same river: one Gaelic, one Welsh and one English.",
   "The English call it the Lea, the Welsh call it Lug, and the Irish call it Lugh after the god. All three are correct and none is the original. The surveyor wants to know which to write on the map. The reeve wants to know what you plan to do about the English one.",
   [
       O("Write all three, in order of age.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 6 }", xp("lifestyle_poet", 15), "eir_resent_clear_effect = yes",
         st=S_FORGIVE, ai=40, ai_mod=[("just", 15), ("patient", 10)]),
       O("Write only the Irish.",
         PRESTIGE_M, "change_variable = { name = eir_resent add = 1 }", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 4 } }",
         st=S_ARROG, ai=20, ai_mod=[("arrogant", 20)]),
       O("Ask a local Welsh bard to decide.",
         PRESTIGE_S, "scope:eir_briton ?= { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 20 } }", xp("lifestyle_poet", 10), "add_character_modifier = { modifier = eir_welsh_tongue_modifier years = 8 }",
         st=S_HUMBLE, ai=30, ai_mod=[("humble", 15)]),
       O("Tell the surveyor to stop wasting your time.",
         STRESS_DOWN, "add_prestige = minor_prestige_loss", st=S_HARD, ai=20, ai_mod=[("lazy", 10), ("impatient", 15)]),
   ],
   "learning", gate=CELTBR + "\nhas_variable = eir_recelt", cooldown=15, immediate=CONQ_COUNTY)

ev(497, "A Saxon Poet Learns Irish",
   "A young English poet has begun writing verse in Irish, and the old women of the county are not sure whether to laugh or weep.",
   "He is clumsy and charming and he is wrong about half the grammar. But he has heard the old songs and decided the English ones are worse. He has asked to join your poets. His father has asked you to stop him. The conquered county is watching to see which of you wins.",
   [
       O("Take him as an apprentice and be proud of it.",
         PRESTIGE_M, xp("lifestyle_poet", 30), "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 12 } }", "eir_resent_clear_effect = yes",
         gate=FILI, st=S_HUMBLE, ai=45, ai_mod=[("humble", 15), ("compassionate", 10)]),
       O("Offer him a place at court and a good teacher.",
         PRESTIGE_S, xp("lifestyle_poet", 15), "add_character_modifier = { modifier = eir_bardic_circuit_modifier years = 6 }", st=S_GEN, ai=40),
       O("Let his father have his way.",
         STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", st=S_CONTENT, ai=20),
       O("Make him write a poem about the conquest.",
         PRESTIGE_S, luck("t497w", "It is surprisingly good", "add_prestige = medium_prestige_gain\nadd_trait_xp = { trait = lifestyle_poet value = 25 }\neir_resent_clear_effect = yes",
                           "t497l", "It is surprisingly bitter", "add_prestige = minor_prestige_loss\nchange_variable = { name = eir_resent add = 1 }", p=50, bonus=(15, "learning >= 12")),
         st=S_ARROG, ai=30, ai_mod=[("arrogant", 10)]),
   ],
   "learning", gate=FOREIGN + "\nhas_variable = eir_recelt", cooldown=15, immediate=CONQ_COUNTY)

ev(498, "The Old Roman Road",
   "Your engineers have found the paving of a Roman road under the turf, and it runs straight toward the next kingdom.",
   "It was built by men who thought the island would be theirs forever, and it has outlasted them by four hundred years. It would need only a little repair to carry a cart, a column of soldiers and a poet's circuit from one end of the county to the other. The Britons say it is theirs. The Saxons say it is theirs. The Irish say that a road is a road.",
   [
       O("Repair it and put a toll-house at the end.",
         GOLD_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_roman_road_modifier years = 15 } }", PRESTIGE_S, GAIN_S,
         gate="gold >= 100", st=S_SHREWD, ai=40, ai_mod=[("diligent", 15)]),
       O("Repair it, and make it free to every pilgrim.",
         GOLD_S, PIETY_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_roman_road_modifier years = 10 } }", "add_character_modifier = { modifier = eir_pilgrim_modifier years = 6 }",
         st=S_GEN, ai=30, ai_mod=[("generous", 15), ("zealous", 10)]),
       O("Tear it up for building stone.",
         GAIN_M, "add_prestige = minor_prestige_loss", st=S_GREED, ai=15, ai_mod=[("greedy", 20), ("lazy", 10)]),
       O("March an army along it as a demonstration.",
         PRESTIGE_M, "add_dread = minor_dread_gain", "scope:eir_conq_county ?= { change_county_control = minor_county_control_gain }",
         gate="martial >= 9", st=S_BRAVE, ai=30, ai_mod=[("brave", 15), ("ambitious", 10)]),
   ],
   "stewardship", gate=FOREIGN + "\nhas_variable = eir_recelt", cooldown=25, immediate=CONQ_COUNTY)

ev(499, "The Bishop's Choice",
   "The bishop of the conquered diocese must decide whether to say Mass in Latin, Irish or English.",
   "It is a small thing, and it is not small. A priest who says Mass in Irish is a Gael. A priest who says it in English is an Englishman. A priest who says it in Latin is a bishop, and he wishes to remain one. He has asked you to choose, which is cowardly, and which you cannot decline.",
   [
       O("Let the Mass be said in Latin, with a sermon in each tongue.",
         PIETY_S, PRESTIGE_S, "eir_resent_clear_effect = yes", "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 6 }", st=S_PATIENT, ai=45, ai_mod=[("patient", 15), ("zealous", 10)]),
       O("Insist the sermon be in Irish.",
         PIETY_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 8 } }", "change_variable = { name = eir_resent add = 1 }",
         st=S_ARROG, ai=20, ai_mod=[("arrogant", 15), ("stubborn", 10)]),
       O("Let each parish choose.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 6 }", "eir_resent_clear_effect = yes", st=S_FORGIVE, ai=35, ai_mod=[("just", 15), ("humble", 10)]),
       O("Refuse to decide.",
         STRESS_UP, "add_piety = minor_piety_loss", st=S_CRAVEN, ai=10),
   ],
   "faith", gate=FOREIGN + "\nhas_variable = eir_recelt\npiety >= 50", cooldown=20, immediate=CONQ_COUNTY)

# =============================================================================
# CEREMONIES OF THE NEW DECISIONS (0500-0515)
# =============================================================================
ev(500, "A Triumph in the Conquered Capital",
   "The Gaelic host marches through the gates of a captured city while the conquered watch.",
   "You have not done this before, and neither has anyone else in Ireland. The old kings took cattle and went home. You have taken a city, and you intend to stay. The poets have composed three songs for the procession. The captured townsmen stand along the road, silent. Some are weeping. A few are, unwillingly, impressed.",
   [
       O("Ride in on a white horse, crowned with gold.",
         "give_nickname = nick_eir_triumphant", PRESTIGE_L, "eir_triumph_glory_effect = yes", "add_dread = minor_dread_gain", "eir_world_reacts_effect = yes",
         st=S_ARROG, ai=40, ai_mod=[("arrogant", 20), ("ambitious", 15)]),
       O("Walk bareheaded behind the relics of the saints.",
         PIETY_L, PRESTIGE_M, "eir_triumph_glory_effect = yes", "add_character_modifier = { modifier = eir_saints_blessing_modifier years = 8 }", xp("lifestyle_mystic", 25),
         st=S_HUMBLE, ai=30, ai_mod=[("humble", 20), ("zealous", 15)]),
       O("Feed the whole city at your own expense.",
         GOLD_M, PRESTIGE_L, "eir_triumph_glory_effect = yes", "add_character_modifier = { modifier = eir_two_peoples_modifier years = 10 }", "eir_resent_clear_effect = yes",
         gate="gold >= 150", st=S_GEN, ai=35, ai_mod=[("generous", 25)]),
       O("Let the poets sing it, and the city listen.",
         PRESTIGE_L, "eir_triumph_glory_effect = yes", "eir_legend_title_effect = { TITLE = primary_title }", xp("lifestyle_poet", 40),
         gate=FILI, st=S_HUMBLE, ai=35),
       O("Make the captured lords kneel in the market-place.",
         "add_dread = major_dread_gain", PRESTIGE_L, "eir_triumph_glory_effect = yes", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 10 } }",
         "change_variable = { name = eir_resent add = 2 }", st=S_HARD, ai=15, ai_mod=[("sadistic", 25), ("callous", 20)]),
   ],
   "legend", guarded=False, immediate=CONQ_COUNTY)

ev(501, "The Victory Cairn",
   "Your soldiers are piling stones on a hill above the conquered town, each man bringing one.",
   "It is the oldest custom there is: a cairn marks where a battle was won, and each man who fought adds a stone. In a hundred years the pile will be a hill, and no one will remember which stone was whose. The poets say that is the point.",
   [
       O("Place the first stone yourself and speak the names of the fallen.",
         PRESTIGE_M, PIETY_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cairn_county_modifier years = 20 } }", "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 4 }",
         st=S_HUMBLE, ai=40, ai_mod=[("humble", 15), ("compassionate", 10)]),
       O("Carve an ogham inscription on the capstone.",
         PRESTIGE_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cairn_county_modifier years = 25 } }", "add_character_modifier = { modifier = eir_royal_ollamh_modifier years = 5 }", xp("lifestyle_poet", 20),
         gate="learning >= 9", st=S_PATIENT, ai=30),
       O("Have the monks bless the stones and raise a cross.",
         PIETY_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cairn_county_modifier years = 15 } }", PRESTIGE_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 8 } }",
         st=S_ZEAL, ai=35, ai_mod=[("zealous", 20)]),
       O("Bury the enemy's captured banners under it.",
         PRESTIGE_M, "add_dread = minor_dread_gain", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cairn_county_modifier years = 20 } }",
         st=S_ARROG, ai=25, ai_mod=[("arrogant", 15)]),
   ],
   "legend", guarded=False)

ev(502, "The Colonists Arrive",
   "A long line of carts, cattle and children comes up the road to the conquered county.",
   "Gaelic families, three hundred of them, led by a grey-bearded priest who has promised to say Mass for them in the open until there is a church. They have chosen their land by lot. They have been told that it will not be easy and that the natives will not welcome them. They have come anyway, because there is no land left at home.",
   [
       O("Receive them yourself, and share the first meal.",
         PRESTIGE_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_gaelic_settlers_modifier years = 12 } }", xp("lifestyle_reveler", 15), "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 3 }",
         st=S_GEN, ai=40, ai_mod=[("generous", 20)]),
       O("Give them land taken from the unfriendly thanes.",
         "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_gaelic_settlers_modifier years = 15 } }", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_cultural_resentment_modifier years = 6 } }", PRESTIGE_S,
         "change_variable = { name = eir_resent add = 1 }", st=S_HARD, ai=25, ai_mod=[("callous", 15), ("ambitious", 10)]),
       O("Set them in a ring of new villages along the road.",
         GOLD_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_gaelic_settlers_modifier years = 12 } }", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_roman_road_modifier years = 8 } }",
         st=S_SHREWD, ai=35, ai_mod=[("diligent", 15)]),
       O("Ask the priest to bless the land and the natives together.",
         PIETY_M, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_gaelic_settlers_modifier years = 10 } }", "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_saxon_moot_modifier years = 8 } }",
         "eir_resent_clear_effect = yes", st=S_ZEAL, ai=35, ai_mod=[("zealous", 15), ("compassionate", 10)]),
   ],
   "court", guarded=False)

ev(503, "The Colony Takes Root",
   "The children of the Gaelic settlers are playing with the local children, and the language of the game is Irish.",
   "It took eight years. The first winter was hard, the second was lean, and the third was the year the English reeve's son married the settlers' daughter. Now there is a church with a bell, a market on Fridays and an alehouse where both languages are spoken and neither is spoken well. The county has changed, and nobody can say quite when.",
   [
       O("Declare the county Gaelic in law and custom.",
         "eir_colony_convert_effect = yes", PRESTIGE_L, "eir_recelt_bump_effect = yes", "add_character_modifier = { modifier = eir_tongue_restorer_modifier years = 8 }",
         st=S_AMBIT, ai=45, ai_mod=[("ambitious", 15)]),
       O("Let the two peoples keep their own customs, side by side.",
         "eir_colony_convert_effect = yes", PRESTIGE_M, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 12 }", "eir_resent_clear_effect = yes",
         st=S_FORGIVE, ai=35, ai_mod=[("just", 20), ("humble", 10)]),
       O("Reward the settlers' priest with a church of his own.",
         "eir_colony_convert_effect = yes", PIETY_M, GOLD_S, "add_character_modifier = { modifier = eir_saints_blessing_modifier years = 6 }",
         st=S_ZEAL, ai=30, ai_mod=[("zealous", 20)]),
       O("Tax the colony more heavily. It can afford it.",
         "eir_colony_convert_effect = yes", GAIN_M, "add_character_modifier = { modifier = eir_cain_tribute_modifier years = 5 }",
         st=S_GREED, ai=20, ai_mod=[("greedy", 20)]),
   ],
   "legend", guarded=False, gate="has_variable = eir_colony_county")

ev(504, "The Feast of the Three Peoples",
   "Gaels, Britons and English have all been invited to the same hall, and for one night, none of them is armed.",
   "The seating plan has taken four months. The cooks have been told which dishes may not be served next to which. The poets have been warned that no song may mention anyone's grandfather. The Welsh bard and the Irish harper have been given the same table. It will either be a triumph or a diplomatic incident.",
   [
       O("Open with a toast to the old island, and all its people.",
         PRESTIGE_L, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 10 }", xp("lifestyle_reveler", 40), "eir_world_reacts_effect = yes", "eir_resent_clear_effect = yes",
         st=S_GEN, ai=40, ai_mod=[("gregarious", 20), ("generous", 15)]),
       O("Let the poets sing in all three tongues.",
         PRESTIGE_M, "eir_legend_title_effect = { TITLE = primary_title }", xp("lifestyle_poet", 30), "add_character_modifier = { modifier = eir_insular_song_modifier years = 10 }",
         gate=FILI, st=S_HUMBLE, ai=35),
       O("Settle the three oldest quarrels at the table.",
         luck("t504w", "All three are settled before dawn", "add_prestige = major_prestige_gain\nadd_character_modifier = { modifier = eir_fair_lord_modifier years = 8 }\neir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = 6 }",
              "t504l", "A knife is drawn, and the feast ends badly", "add_prestige = medium_prestige_loss\nadd_stress = minor_stress_gain", p=55, bonus=(25, "diplomacy >= 16")),
         gate="diplomacy >= 10", st=S_PATIENT, ai=30, ai_mod=[("patient", 15), ("calm", 10)]),
       O("Keep the feast short, and the wine watered.",
         PRESTIGE_S, STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 5 }", st=S_CONTENT, ai=25, ai_mod=[("temperate", 20)]),
   ],
   "party", guarded=False)

ev(505, "The Book of Conquests",
   "A poet reads the first chapter of a book that traces your line to the first Gaels who came out of Spain.",
   "It starts with Míl Espáine and his eight sons, and passes through the Fir Bolg, the Tuatha Dé Danann and the Cruthin. It ends with you. It has taken three years and a good many genealogies were improved. The poet reads it in the long voice and does not look up. At the end, there is silence, and then the poets begin to argue about the dates.",
   [
       O("Accept the book as the history of the Gael.",
         PRESTIGE_L, "eir_legend_title_effect = { TITLE = primary_title }", "add_character_modifier = { modifier = eir_book_of_conquests_modifier years = 15 }", xp("lifestyle_poet", 30),
         st=S_ARROG, ai=40, ai_mod=[("arrogant", 15), ("ambitious", 15)]),
       O("Insist on corrections from the monasteries.",
         PIETY_M, PRESTIGE_M, "add_character_modifier = { modifier = eir_book_of_conquests_modifier years = 10 }", "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 6 }",
         gate="piety >= 100", st=S_HONEST, ai=35, ai_mod=[("honest", 20), ("zealous", 10)]),
       O("Order a gilded copy made for each of your allies.",
         GOLD_M, PRESTIGE_M, "eir_world_reacts_effect = yes", "eir_vassal_opinion_effect = { MODIFIER = eir_shared_spoils_opinion OPINION = 4 }", "add_character_modifier = { modifier = eir_book_of_conquests_modifier years = 12 }",
         gate="gold >= 150", st=S_GEN, ai=30, ai_mod=[("generous", 15)]),
       O("Keep it for yourself, and use it as a weapon of claim.",
         PRESTIGE_S, "add_character_flag = { flag = eir_oath_to_reclaim years = 12 }", "add_character_modifier = { modifier = eir_false_pedigree_modifier years = 5 }",
         st=S_DECEIT, ai=25, ai_mod=[("deceitful", 20), ("ambitious", 15)]),
   ],
   "learning", guarded=False)

ev(506, "The Union Proclaimed",
   "The kings of the Gaels, Britons and Picts have met at a place that belongs to none of them.",
   "A flat green field in the Irish Sea, they say, if there were such a thing. In practice, it is a hall on the border of Man, loaned for the occasion. The hall is full of banners. The conversation is in three languages, the minutes are in Latin, and the oath is in all four. Everyone knows that this will not last. Everyone is swearing it anyway.",
   [
       O("Proclaim the Union in your own name.",
         "give_nickname = nick_eir_island_king", PRESTIGE_L, "add_character_modifier = { modifier = eir_insular_union_modifier years = 30 }", "eir_world_reacts_effect = yes", "trigger_event = { id = eir.0507 days = 60 }",
         st=S_ARROG, ai=35, ai_mod=[("arrogant", 15), ("ambitious", 20)]),
       O("Proclaim it in the names of all the kings together.",
         PRESTIGE_L, PIETY_M, "add_character_modifier = { modifier = eir_insular_union_modifier years = 25 }", "eir_world_reacts_effect = yes", "eir_vassal_opinion_effect = { MODIFIER = eir_shared_spoils_opinion OPINION = 8 }",
         "trigger_event = { id = eir.0507 days = 60 }", st=S_HUMBLE, ai=40, ai_mod=[("humble", 20), ("gregarious", 15)]),
       O("Have the poets write the Union into the genealogies.",
         PRESTIGE_M, "eir_legend_title_effect = { TITLE = primary_title }", xp("lifestyle_poet", 40), "add_character_modifier = { modifier = eir_insular_union_modifier years = 25 }",
         "trigger_event = { id = eir.0507 days = 60 }", gate=FILI, st=S_HUMBLE, ai=30),
       O("Bind each king with a different oath.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_insular_union_modifier years = 20 }", GAIN_S,
         "trigger_event = { id = eir.0507 days = 60 }", gate="OR = {\nintrigue >= 12\nhas_trait = deceitful\nhas_trait = shrewd\n}", st=S_DECEIT, ai=25, ai_mod=[("deceitful", 20), ("shrewd", 15)]),
   ],
   "legend", guarded=False)

ev(507, "The Princes Answer",
   "The Welsh and Cornish princes have sent their replies to the Union, and they are not all friendly.",
   "Gwynedd has sent a poem. Dyfed has sent a bishop. Cornwall has sent a bill for the tin tolls. The sons of the dead king of Strathclyde have sent nothing, which in their tradition means a great deal. The Union is a fine idea. It is also a request that three proud peoples forget their separate pasts, and that is not a small ask.",
   [
       O("Answer each in kind: a poem, a bishop, a bill and a silence.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 12 }", xp("lifestyle_poet", 20), "eir_world_reacts_effect = yes",
         gate=FILI, st=S_HUMBLE, ai=35),
       O("Offer each prince a hostage and a seat on the Union's council.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 15 }", "eir_vassal_opinion_effect = { MODIFIER = eir_shared_spoils_opinion OPINION = 4 }", GOLD_S,
         gate="diplomacy >= 10", st=S_PATIENT, ai=40, ai_mod=[("patient", 15), ("calm", 10)]),
       O("Warn the silent ones that silence is not neutrality.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "add_character_flag = { flag = eir_oath_to_reclaim years = 10 }", GAIN_S,
         st=S_HARD, ai=20, ai_mod=[("ambitious", 15), ("wrathful", 10)]),
       O("Let the Union speak for itself.",
         STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 4 }", st=S_CONTENT, ai=30, ai_mod=[("content", 15)]),
   ],
   "diplomacy", guarded=False)

ev(509, "The Island Crown",
   "A crown has been made for a kingdom that never existed, and today it is placed on your head.",
   "It is plain gold, a circlet with three stones: green for Ireland, red for Britain, blue for the sea between. The goldsmith has been working on it for a year. The archbishops are present. The old kings of the Gaels and the Britons are present, in the form of their descendants. Nobody has ever been crowned King of the Island of the Mighty before, because there has never been such a kingdom.",
   [
       O("Wear the crown, and the title that goes with it.",
         "give_nickname = nick_eir_island_king", PRESTIGE_L, PIETY_M, "add_character_modifier = { modifier = eir_island_crown_modifier years = 40 }", "eir_world_reacts_effect = yes",
         st=S_ARROG, ai=45, ai_mod=[("arrogant", 20), ("ambitious", 20)]),
       O("Refuse the crown for yourself, and place it on the Hill of Tara.",
         PRESTIGE_L, PIETY_L, "add_character_modifier = { modifier = eir_island_crown_modifier years = 30 }", "eir_legend_title_effect = { TITLE = primary_title }",
         st=S_HUMBLE, ai=20, ai_mod=[("humble", 25)]),
       O("Split the stones among the three crowns that supported you.",
         PRESTIGE_L, "add_character_modifier = { modifier = eir_island_crown_modifier years = 30 }", "eir_vassal_opinion_effect = { MODIFIER = eir_shared_spoils_opinion OPINION = 10 }", "eir_world_reacts_effect = yes",
         st=S_GEN, ai=30, ai_mod=[("generous", 20)]),
       O("Have the poets compose a new genealogy for the line.",
         PRESTIGE_M, xp("lifestyle_poet", 40), "eir_legend_title_effect = { TITLE = primary_title }", "add_character_modifier = { modifier = eir_island_crown_modifier years = 30 }",
         gate=FILI, st=S_HUMBLE, ai=30),
   ],
   "legend", guarded=False)

ev(510, "The Bridgehead",
   "Your ships have landed at a quiet cove on the British coast, and nobody has noticed yet.",
   "Forty men, a priest, two carpenters and a very nervous interpreter. They have beached on a shelf of shingle below a ruined Roman signal-tower, which will do very well for a fort. In three days they will have a palisade. In a month they will have a harbour. In a year, a war, if you want one.",
   [
       O("Fortify it, and bring the army across.",
         "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_bridgehead_modifier years = 6 } }", PRESTIGE_M, "add_character_modifier = { modifier = eir_beacons_modifier years = 3 }",
         "spawn_army = {\n\tlevies = 600\n\tmen_at_arms = {\n\t\ttype = light_footmen\n\t\tstacks = 2\n\t}\n\tlocation = scope:eir_conq_county.title_province\n\torigin = capital_province\n\tinheritable = no\n\tname = eir_bridgehead_host_name\n}",
         st=S_BRAVE, ai=40, ai_mod=[("brave", 15), ("ambitious", 15)]),
       O("Open negotiations with the local Britons.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 8 }", "scope:eir_briton ?= { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 25 } }",
         st=S_FORGIVE, ai=35, ai_mod=[("gregarious", 15)]),
       O("Use it as a base for a swift raid.",
         GAIN_M, "add_dread = minor_dread_gain", PRESTIGE_S, "add_character_modifier = { modifier = eir_raider_infamy_modifier years = 4 }",
         st=S_WRATH, ai=25, ai_mod=[("wrathful", 15), ("greedy", 10)]),
       O("Hold it quietly, and tell nobody.",
         "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 4 }", STRESS_DOWN, st=S_DECEIT, ai=25, ai_mod=[("deceitful", 15)]),
   ],
   "war", guarded=False, immediate="random_sub_realm_county = {\n\tlimit = { is_coastal_county = yes }\n\tsave_scope_as = eir_conq_county\n}\nif = {\n\tlimit = { NOT = { exists = scope:eir_conq_county } }\n\tcapital_county ?= { save_scope_as = eir_conq_county }\n}")

ev(511, "The Foster-Sons of the Princes Arrive",
   "The sons of three British princes have been brought to your court, and they do not look happy.",
   "They are ten, eleven and thirteen, and they have been told it is an honour. They are also very sure it is a punishment. Fosterage is how the Irish make peace, and how the Britons used to, before the Romans taught them to take hostages instead. The three boys are not sure which they are. You will be their guardian for the next ten years.",
   [
       O("Raise them with your own children.",
         "add_character_modifier = { modifier = eir_foster_bond_modifier years = 15 }", PRESTIGE_M, "eir_vassal_opinion_effect = { MODIFIER = eir_fostered_opinion OPINION = 5 }", xp("lifestyle_reveler", 15),
         st=S_KIND, ai=40, ai_mod=[("compassionate", 20), ("patient", 10)]),
       O("Educate them at the monastery, in Irish and Latin.",
         PIETY_M, "add_character_modifier = { modifier = eir_welsh_tongue_modifier years = 10 }", PRESTIGE_S, "scope:eir_conq_county ?= { add_county_modifier = { modifier = eir_hedge_schools_modifier years = 8 } }",
         st=S_ZEAL, ai=35, ai_mod=[("zealous", 20)]),
       O("Train them as warriors, in the Irish way.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_war_poem_modifier years = 8 }", xp("lifestyle_blademaster", 15), "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 3 }",
         gate="martial >= 8", st=S_BRAVE, ai=30, ai_mod=[("brave", 15)]),
       O("Keep them under close guard. They are hostages, whatever you call them.",
         "add_character_modifier = { modifier = eir_hostage_peace_modifier years = 10 }", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_hard_justice_opinion OPINION = -2 }",
         st=S_HARD, ai=25, ai_mod=[("paranoid", 20), ("callous", 10)]),
   ],
   "hostage", guarded=False)

ev(513, "The Raid on the Saxon Coast",
   "Your longboats have come back from the English coast with plunder, prisoners and a story.",
   "It was a fine raid, the sort the old kings would have been proud of. Twelve boats, a night landing, a monastery taken without a fight, and three hundred head of cattle driven off before the dogs woke. The prisoners are mostly boys. The cattle are mostly lame. The story is enormous.",
   [
       O("Divide the spoils among the raiders, and keep a share.",
         GAIN_M, PRESTIGE_M, "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 4 }", xp("lifestyle_hunter", 15),
         st=S_GREED, ai=40, ai_mod=[("greedy", 15), ("brave", 10)]),
       O("Free the prisoners and send them home with a gift.",
         PRESTIGE_M, PIETY_M, "add_character_modifier = { modifier = eir_honour_restored_modifier years = 5 }", "eir_trait_effect = { TRAIT = compassionate OPPOSITE = callous CHANCE = 25 }",
         st=S_KIND, ai=25, ai_mod=[("compassionate", 25)]),
       O("Ransom the best of them to their families.",
         GAIN_M, GAIN_S, PRESTIGE_S, "add_character_modifier = { modifier = eir_norse_spoils_modifier years = 3 }", st=S_SHREWD, ai=35, ai_mod=[("shrewd", 15)]),
       O("Give the plunder to the Church and keep only the glory.",
         PIETY_L, PRESTIGE_S, "add_character_modifier = { modifier = eir_saints_blessing_modifier years = 4 }", st=S_ZEAL, ai=25, ai_mod=[("zealous", 20)]),
   ],
   "war", guarded=False)

ev(514, "Acclaimed in the Conquered Capital",
   "The bells of a foreign cathedral ring out in your name.",
   "It was not planned. The bishop came out to the steps, saw the army, saw you and made a small, complicated decision. He began the Te Deum. The choir came in on cue. The people of the city, who had been wondering whether to rebel, found themselves singing along. It is not a coronation. It is something more useful.",
   [
       O("Take the title offered by the city.",
         PRESTIGE_L, PIETY_M, "eir_triumph_glory_effect = yes", "add_character_modifier = { modifier = eir_conqueror_crowned_modifier years = 20 }", "eir_world_reacts_effect = yes",
         st=S_AMBIT, ai=45, ai_mod=[("ambitious", 20)]),
       O("Thank the bishop and keep the Gaelic titles.",
         PRESTIGE_M, PIETY_M, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 10 }", "eir_resent_clear_effect = yes",
         st=S_HUMBLE, ai=30, ai_mod=[("humble", 20), ("content", 10)]),
       O("Have the poets turn the acclamation into a hundred verses.",
         PRESTIGE_M, "eir_legend_title_effect = { TITLE = primary_title }", xp("lifestyle_poet", 30), "add_character_modifier = { modifier = eir_insular_song_modifier years = 8 }",
         gate=FILI, st=S_HUMBLE, ai=30),
       O("Quietly note which of the city's lords did not sing.",
         "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 5 }", PRESTIGE_S, "add_dread = minor_dread_gain", st=S_DECEIT, ai=25, ai_mod=[("paranoid", 20), ("deceitful", 15)]),
   ],
   "legend", guarded=False)

ev(515, "The Sea-Road Opens",
   "The first ferry has crossed from Ulster to Galloway in a single day, with cattle and a bishop.",
   "The captain wept when the quay came into view. He had been told it could not be done, and then told it could be done by a better captain. He is now, he says, the better captain. He has a letter in his sleeve for you, from the abbot of Whithorn, who says the boat was an answer to prayer.",
   [
       O("Declare a pilgrim's holiday and open the quays to all.",
         PIETY_M, "add_character_modifier = { modifier = eir_sea_road_modifier years = 15 }", "add_character_modifier = { modifier = eir_pilgrim_modifier years = 8 }", xp("lifestyle_traveler", 25),
         st=S_GEN, ai=35, ai_mod=[("generous", 15), ("zealous", 15)]),
       O("Tax each crossing and use the money for the beacons.",
         GAIN_M, "add_character_modifier = { modifier = eir_sea_road_modifier years = 12 }", "every_realm_county = {\n\tlimit = { is_coastal_county = yes }\n\tadd_county_modifier = { modifier = eir_beacon_county_modifier years = 10 }\n}",
         st=S_SHREWD, ai=40, ai_mod=[("shrewd", 15), ("greedy", 10)]),
       O("Send the first army across, to prove the road works.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_sea_road_modifier years = 12 }", "add_character_modifier = { modifier = eir_beacons_modifier years = 4 }",
         gate="martial >= 8", st=S_BRAVE, ai=30, ai_mod=[("brave", 15), ("ambitious", 10)]),
       O("Name the captain Master of the Narrow Sea.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_sea_road_modifier years = 15 }", xp("lifestyle_traveler", 15), "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 4 }",
         st=S_GEN, ai=35, ai_mod=[("generous", 20)]),
   ],
   "stewardship", guarded=False)

# =============================================================================
# THE UNION AND ITS TENSIONS (0516-0527)
# =============================================================================
ev(516, "The Quarrel of the Tongues",
   "The Gaels and the Britons of the Union have started a quarrel about which language should be used in the council.",
   "It began with a Welsh poet who corrected an Irish judge's grammar. It continued when the Irish judge corrected the poet's. By the end of the week there were three factions, a book of grievances and a seating chart that was drawn up twice. The Union is meant to be a marriage of equals. The language is the first thing to go wrong.",
   [
       O("Declare that every speech be made in the speaker's own tongue, with an interpreter.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 8 }", GOLD_S, xp("lifestyle_poet", 15),
         st=S_FORGIVE, ai=40, ai_mod=[("just", 20), ("patient", 10)]),
       O("Make Latin the common speech, and let each add a verse in their own.",
         PRESTIGE_S, PIETY_S, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 6 }", st=S_PATIENT, ai=35),
       O("Insist on Irish, since it is the language of the Union's founder.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_welsh_resentment_modifier years = 8 }", "change_variable = { name = eir_resent add = 1 }",
         st=S_ARROG, ai=15, ai_mod=[("arrogant", 25)]),
       O("Hold a poetry contest and let the winner's language preside.",
         luck("t516w", "A Gaelic poet wins gracefully", "add_prestige = medium_prestige_gain\nadd_character_modifier = { modifier = eir_two_peoples_modifier years = 5 }",
              "t516l", "A Welsh bard wins, and a few Gaels sulk", "add_prestige = minor_prestige_gain\nadd_character_modifier = { modifier = eir_welsh_tongue_modifier years = 8 }", p=50, bonus=(15, "learning >= 12")),
         gate=FILI, st=S_HUMBLE, ai=30),
   ],
   "court", gate=UNION, cooldown=15)

ev(517, "A Welsh Prince Pays Homage",
   "A prince of Dyfed has come to your hall in person, with his harper and his hounds, to swear the Union.",
   "He is not young and he is not poor. He has no need of a protector. He says he has simply decided that the Welsh have been alone too long. His harper plays a march that none of your people knows, and the prince's hounds bay at your wolfhounds, who bay back with dignity.",
   [
       O("Receive him as an equal and a friend.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 15 }", "scope:eir_briton ?= { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }", xp("lifestyle_reveler", 20),
         st=S_GEN, ai=45, ai_mod=[("gregarious", 20), ("humble", 10)]),
       O("Let him swear fealty on the relics.",
         PIETY_M, PRESTIGE_S, "add_hook = { target = scope:eir_briton type = strong_hook }", "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 10 }",
         st=S_ZEAL, ai=30, ai_mod=[("zealous", 15)]),
       O("Ask for his son as a foster-child.",
         "add_character_modifier = { modifier = eir_foster_bond_modifier years = 12 }", PRESTIGE_S, "add_hook = { target = scope:eir_briton type = favor_hook }",
         st=S_SHREWD, ai=35, ai_mod=[("shrewd", 15)]),
       O("Accept his homage, but ask him to leave the hounds outside.",
         PRESTIGE_S, "scope:eir_briton ?= { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -8 } }", STRESS_DOWN, st=S_ARROG, ai=15, ai_mod=[("arrogant", 15)]),
   ],
   "diplomacy", gate=UNION + "\n" + BRIT_ANY, cooldown=20, immediate=PICK_BRIT, portraits=BRIT_P)

ev(518, "The Cornish Tin Revolt",
   "The Cornish tinners have downed tools and refuse to pay the Union's duty.",
   "They say the duty was a promise made by kings, not by the Cornish. They say the Union is a fine idea and that it does not require them to be poorer. Eight hundred men have walked out of the stannaries and are sitting on the hill with their arms folded. The price of tin is rising by the hour.",
   [
       O("Cut the duty by half, and ask the Cornish to keep the peace.",
         "add_character_modifier = { modifier = eir_fair_lord_modifier years = 6 }", PRESTIGE_S, "remove_short_term_gold = minor_gold_value", st=S_GEN, ai=40, ai_mod=[("generous", 15), ("patient", 10)]),
       O("Send in the Irish garrison to compel the tinners.",
         "add_dread = medium_dread_gain", GAIN_M, "add_character_modifier = { modifier = eir_welsh_resentment_modifier years = 8 }", "change_variable = { name = eir_resent add = 1 }",
         st=S_HARD, ai=15, ai_mod=[("callous", 20), ("wrathful", 15)]),
       O("Meet the Cornish leaders in a stannary court.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_two_peoples_modifier years = 8 }", "eir_trait_effect = { TRAIT = just OPPOSITE = arbitrary CHANCE = 25 }",
         gate="diplomacy >= 10", st=S_PATIENT, ai=40, ai_mod=[("just", 20), ("calm", 10)]),
       O("Pay the tinners in Irish cattle until the duty is settled.",
         GOLD_M, "add_character_modifier = { modifier = eir_hospitality_modifier years = 5 }", PRESTIGE_S, st=S_GEN, ai=25),
   ],
   "stewardship", gate=UNION, cooldown=20)

ev(519, "The Last Pictish Family",
   "In a high glen in the north, one family still sings a song that no one else understands.",
   "The grandmother says it is a lullaby. The monk says it is a hymn. The traveller says it is a spell. It has no Gaelic words in it and no Welsh ones either. It is, as far as anyone can tell, the last live sentence in the language of a people who ruled the north for a thousand years. They are not asking for anything.",
   [
       O("Send a monk with ink to write it down.",
         PIETY_S, PRESTIGE_M, "add_character_modifier = { modifier = eir_pictish_memory_modifier years = 15 }", xp("lifestyle_poet", 25),
         st=S_HUMBLE, ai=40, ai_mod=[("humble", 15), ("compassionate", 15)]),
       O("Invite the family to your hall and give them a patron's pension.",
         GOLD_S, PRESTIGE_M, "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 4 }", "eir_legend_title_effect = { TITLE = primary_title }",
         st=S_GEN, ai=35, ai_mod=[("generous", 20)]),
       O("Leave them to the glen and its quiet.",
         STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", st=S_CONTENT, ai=25),
       O("Have them taught Irish for their own good.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_welsh_resentment_modifier years = 4 }", "eir_trait_effect = { TRAIT = arbitrary OPPOSITE = just CHANCE = 15 }",
         st=S_ARROG, ai=10, ai_mod=[("arrogant", 20)]),
   ],
   "legend", gate=UNION, cooldown=30)

ev(520, "The Council of the Insular Kings",
   "The kings of the Union have gathered for their annual council, and the agenda has a hundred items.",
   "There is the question of Easter, which will not die. There is the question of the border, which has not been settled since the Romans. There is the question of the tin duty, the cattle duty and a boy who was fostered in the wrong hall. There is a long list of minor offences. The chairman, who is you, has a headache.",
   [
       O("Settle the most difficult dispute yourself, on the spot.",
         luck("t520w", "The judgement is accepted by all", "add_prestige = major_prestige_gain\nadd_character_modifier = { modifier = eir_fair_lord_modifier years = 10 }\nadd_legitimacy = medium_legitimacy_gain",
              "t520l", "The judgement pleases nobody", "add_prestige = minor_prestige_loss\nadd_stress = minor_stress_gain", p=55, bonus=(25, "learning >= 14")),
         gate="learning >= 9", st=S_ARROG, ai=30, ai_mod=[("arrogant", 10), ("just", 15)]),
       O("Appoint a committee of bishops and poets.",
         PIETY_S, PRESTIGE_M, xp("lifestyle_poet", 15), "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 6 }",
         st=S_PATIENT, ai=40, ai_mod=[("patient", 15)]),
       O("Turn the council into a feast and put the quarrels off.",
         PRESTIGE_S, xp("lifestyle_reveler", 25), "add_character_modifier = { modifier = eir_hospitality_modifier years = 4 }", STRESS_DOWN,
         st=S_GEN, ai=30, ai_mod=[("gregarious", 15), ("lazy", 10)]),
       O("Walk out. The Union will keep itself.",
         STRESS_DOWN, "add_prestige = medium_prestige_loss", "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = -4 }", st=S_CRAVEN, ai=10),
   ],
   "court", gate=UNION, cooldown=10)

ev(521, "A Gaelic Monk in Northumbria",
   "An Irish monk has established a small monastery in the north of England, and the locals are coming in droves.",
   "He has no land and no permission, just a hut, a bell and a very good singing voice. The Saxon farmers think he is a saint. The Saxon thane thinks he is a nuisance. The monk thinks everything is going quite well. He has sent a letter to ask whether you could send him a second bell.",
   [
       O("Send the bell, and two more monks.",
         GOLD_S, PIETY_M, "add_character_modifier = { modifier = eir_missionary_glory_modifier years = 5 }", PRESTIGE_S, st=S_ZEAL, ai=40, ai_mod=[("zealous", 20)]),
       O("Send a letter to the thane, asking him to be patient.",
         PRESTIGE_S, "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 3 }", xp("lifestyle_mystic", 15), st=S_PATIENT, ai=30),
       O("Send a small garrison to protect him.",
         GOLD_S, PRESTIGE_S, "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 3 }", "add_piety = minor_piety_loss",
         gate="martial >= 8", st=S_BRAVE, ai=25, ai_mod=[("brave", 15)]),
       O("Ignore the letter. He will manage.",
         STRESS_DOWN, "add_piety = minor_piety_loss", st=S_CONTENT, ai=15, ai_mod=[("lazy", 15)]),
   ],
   "faith", gate=CELTBR + "\npiety >= 60", cooldown=20)

ev(522, "Your Name in Three Languages",
   "The poets of three nations have each composed a poem about you, and they have all asked to read it first.",
   "The Irish poem is in the old style and rhymes in four ways. The Welsh poem is in strict metre and has no hero, only landscape. The Latin poem, by a monk of Whithorn, calls you the new Constantine. You are not sure how to respond to being compared to a man who built a city for himself.",
   [
       O("Receive them all at the same feast.",
         PRESTIGE_L, xp("lifestyle_poet", 30), xp("lifestyle_reveler", 20), "add_character_modifier = { modifier = eir_insular_song_modifier years = 10 }", "eir_legend_title_effect = { TITLE = primary_title }",
         st=S_GEN, ai=40, ai_mod=[("gregarious", 15), ("generous", 10)]),
       O("Ask them to write a single poem together.",
         PRESTIGE_M, "eir_court_opinion_effect = { MODIFIER = eir_poet_praise_opinion OPINION = 6 }", xp("lifestyle_poet", 20), "add_character_modifier = { modifier = eir_insular_song_modifier years = 12 }",
         gate=FILI, st=S_HUMBLE, ai=35, ai_mod=[("humble", 15)]),
       O("Ask the Latin poet to omit the Constantine comparison.",
         PRESTIGE_S, PIETY_S, STRESS_DOWN, st=S_HUMBLE, ai=30, ai_mod=[("humble", 20)]),
       O("Keep the Latin poem. It is the best.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_false_pedigree_modifier years = 4 }", st=S_ARROG, ai=25, ai_mod=[("arrogant", 20)]),
   ],
   "legend", gate=UNION, cooldown=25)

ev(523, "The Banner of the Three Crowns",
   "A seamstress has finished the banner of the Union, and the three emblems on it do not agree.",
   "The Irish harp, the Welsh dragon, the Cornish chough: three emblems that have never shared a field. The seamstress has put them in a ring. They look like they are about to have a fight. She wants to know whether to separate them with a Celtic knot, a cross or a very small saint.",
   [
       O("A Celtic knot, to bind them together.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_insular_union_modifier years = 8 }", "eir_make_artifact_effect = { NAME = eir_union_banner_name DESC = eir_union_banner_desc TYPE = tapestry VISUALS = tapestry MODIFIER = eir_union_banner_modifier }",
         st=S_PATIENT, ai=40, ai_mod=[("patient", 10)]),
       O("A cross, to remind them of the Church.",
         PIETY_M, PRESTIGE_S, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 6 }", st=S_ZEAL, ai=35, ai_mod=[("zealous", 20)]),
       O("A very small saint, and let the argument begin.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_hospitality_modifier years = 4 }", xp("lifestyle_mystic", 15), st=S_CONTENT, ai=25),
       O("Choose the dragon. Welsh is the elder tongue.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_welsh_ties_modifier years = 10 }", "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = -3 }",
         st=S_HUMBLE, ai=20, ai_mod=[("humble", 20)]),
   ],
   "court", gate=UNION, cooldown=30)
