"""Update 2, part B: the Norse and the Irish (0440-0455) and the Gaels against the Gaels (0456-0479).
Pulse-fired flavor events (guard flag, cooldown) plus the follow-ups of the new Norse and kingship decisions."""
from ev_h import *
import ev_h
EVENTS = ev_h.EVENTS = []

FILI = "has_global_variable = eir_done_fili"
FOSTER = "has_global_variable = eir_done_fosterage"
NORSE_L = "is_ai = yes\nis_ruler = yes\nhighest_held_title_tier >= tier_county\nculture ?= { has_cultural_pillar = heritage_north_germanic }\nNOT = { this = root }"
NORSE_ANY = "any_ruler = {\n" + NORSE_L.replace("\n", "\n\t").join(["\t", ""]) + "\n}"
RIVAL_L = "is_ai = yes\nis_ruler = yes\nhighest_held_title_tier >= tier_county\nculture = culture:irish\nNOT = { this = root }\nNOT = { is_vassal_of = root }"
RIVAL_ANY = "any_ruler = {\n" + RIVAL_L.replace("\n", "\n\t").join(["\t", ""]) + "\n}"
PICK_NORSE = "random_ruler = {\n\tlimit = {\n" + NORSE_L.replace("\n", "\n\t\t").join(["\t\t", ""]) + "\n\t}\n\tsave_scope_as = eir_norse\n}"
PICK_RIVAL = "random_ruler = {\n\tlimit = {\n" + RIVAL_L.replace("\n", "\n\t\t").join(["\t\t", ""]) + "\n\t}\n\tsave_scope_as = eir_rival\n}"
NORSE_P = "left_portrait = {\n\tcharacter = scope:eir_norse\n\tanimation = personality_bold\n}"
RIVAL_P = "left_portrait = {\n\tcharacter = scope:eir_rival\n\tanimation = personality_bold\n}"
VIKING = "eir_viking_age_trigger = yes\neir_has_coast_trigger = yes\n" + NORSE_ANY

# =============================================================================
# THE NORSE AND THE IRISH
# =============================================================================
ev(440, "The Dubliners' Offer",
   "[eir_norse.GetShortUIName] offers an alliance against your common enemy, with silver and ships as the dowry.",
   "He is the king of a harbour town on a river, and he has a longship for every cow you have. His envoy speaks fluent Irish and uses the proverbs correctly, which is more unsettling than if he had not. The terms are simple: the Norse-Gael will help you against the king next door, and you will not ask him to be a Christian.\n\nThe bishops are listening at the door.",
   [
       O("Accept the pact and share the harbour dues.",
         GAIN_M, "add_character_modifier = { modifier = eir_norse_wife_modifier years = 8 }", "eir_vassal_opinion_effect = { MODIFIER = eir_norse_pact_opinion OPINION = -3 }", PRESTIGE_S,
         "add_piety = minor_piety_loss", st=S_CYN, ai=30, ai_mod=[("cynical", 15), ("greedy", 10)]),
       O("Accept, but only if he is baptised at the font.",
         PIETY_S, PRESTIGE_M, "scope:eir_norse = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 20 } }", "add_character_modifier = { modifier = eir_hospitality_modifier years = 6 }",
         gate="OR = {\ndiplomacy >= 11\nhas_trait = zealous\n}", st=S_ZEAL, ai=35, ai_mod=[("zealous", 20)]),
       O("Ask for his son as a foster-child instead.",
         "scope:eir_norse = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 25 } }", "add_hook = { target = scope:eir_norse type = favor_hook }", PRESTIGE_S, "add_character_modifier = { modifier = eir_foster_bond_modifier years = 10 }",
         gate=FOSTER, st=S_SHREWD, ai=30, ai_mod=[("shrewd", 15)]),
       O("Refuse, and tell the bishops you did.",
         PIETY_M, PRESTIGE_S, "scope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -15 } }",
         st=S_ZEAL, ai=25, ai_mod=[("zealous", 15), ("honest", 10)]),
       O("Take the silver and promise nothing.",
         GAIN_S, "scope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -25 } }", "add_character_modifier = { modifier = eir_raider_infamy_modifier years = 3 }",
         gate="OR = {\nhas_trait = deceitful\nhas_trait = greedy\nintrigue >= 12\n}", st=S_DECEIT, ai=15, ai_mod=[("deceitful", 25), ("greedy", 15)]),
   ],
   "court", gate=VIKING, cooldown=20, immediate=PICK_NORSE, portraits=NORSE_P,
   variants=[("has_trait = zealous", "The envoy speaks fluent Irish and uses the proverbs correctly. He also wears a hammer around his neck and does not tuck it away, which a pious man cannot help but notice. The bishops are listening at the door, and you are quite sure they have noticed too.")])

ev(441, "The Slave Market at the Strand",
   "Norse merchants have set up a market for captives on your coast, and half the buyers are Irish.",
   "The merchants say the trade is old and honourable. The monks say it is an abomination. The kings buy slaves when they need hands for a harvest. The people being sold are mostly Irish, taken from the next county over, the Britons of the west, a few Saxons. They do not look very different from you.",
   [
       O("Buy as many captives as you can, and set them free.",
         GOLD_M, PIETY_L, "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 8 }", "eir_trait_effect = { TRAIT = compassionate OPPOSITE = callous CHANCE = 30 }",
         gate="gold >= 150", st=S_KIND, ai=30, ai_mod=[("compassionate", 25), ("zealous", 10)]),
       O("Raid the market and take the captives for yourself.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "add_character_modifier = { modifier = eir_raider_infamy_modifier years = 4 }", GAIN_S,
         "add_piety = minor_piety_loss", st=S_BRAVE, ai=15, ai_mod=[("brave", 10), ("sadistic", 10)]),
       O("Tax the market and look the other way.",
         GAIN_M, "add_piety = minor_piety_loss", "eir_trait_effect = { TRAIT = callous OPPOSITE = compassionate CHANCE = 25 }",
         st=S_GREED, ai=35, ai_mod=[("greedy", 20), ("callous", 10)]),
       O("Forbid the sale of baptised Christians, and hang the first offender.",
         PIETY_M, PRESTIGE_S, "add_dread = minor_dread_gain", "eir_vassal_opinion_effect = { MODIFIER = eir_norse_pact_opinion OPINION = -2 }",
         gate="piety >= 80", st=S_ZEAL, ai=30, ai_mod=[("zealous", 20), ("just", 15)]),
   ],
   "dread", gate=VIKING, cooldown=15, immediate=PICK_NORSE)

ev(442, "A Norse-Gael Bride",
   "A great Norse-Gaelic family offers a daughter to your house.",
   "She is called Gormlaith by her Irish mother and Gunnhild by her Norse father, and she answers to both. Her family holds a fortified harbour and sixty ships. They want a king who will not burn their houses. You want a navy. It could be a very good match.\n\nThe bishop sniffs and says the girl has probably never been properly baptised.",
   [
       O("Accept the match, and the dowry in ships.",
         "add_character_modifier = { modifier = eir_norse_wife_modifier years = 15 }", PRESTIGE_M, "add_piety = minor_piety_loss", "add_character_modifier = { modifier = eir_hebridean_ties_modifier years = 10 }",
         gate="", st=S_AMBIT, ai=35, ai_mod=[("ambitious", 20)]),
       O("Offer the match to your heir.",
         "add_character_modifier = { modifier = eir_norse_wife_modifier years = 12 }", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_norse_pact_opinion OPINION = -2 }", PIETY_S,
         gate="exists = primary_heir", st=S_SHREWD, ai=40, ai_mod=[("shrewd", 15)]),
       O("Insist that she and her household be baptised first.",
         PIETY_M, PRESTIGE_S, "add_character_modifier = { modifier = eir_hospitality_modifier years = 6 }",
         luck("t442w", "She agrees, with a smile", "add_character_modifier = { modifier = eir_norse_wife_modifier years = 12 }\nadd_prestige = minor_prestige_gain",
              "t442l", "Her father takes offence", "add_prestige = minor_prestige_loss", p=55, bonus=(15, "diplomacy >= 12")),
         st=S_ZEAL, ai=30, ai_mod=[("zealous", 20)]),
       O("Decline, politely.",
         PRESTIGE_S, STRESS_DOWN, "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", st=S_CONTENT, ai=25, ai_mod=[("content", 15), ("chaste", 10)]),
   ],
   "marriage", gate=VIKING, cooldown=20)

ev(443, "A Longphort on the Border",
   "The Norse have built a fortified camp on a river-bend at the edge of your land.",
   "They did it in a month, with stakes and turf and the stones of a ruined church. There are a hundred ships drawn up on the mud, and a market is already forming under the walls. The local farmers sell them butter and cattle at an excellent price. The local lord, who is you, has not been consulted.",
   [
       O("Burn it before the walls are finished.",
         luck("t443w", "The camp burns, and the ships with it", "add_prestige = medium_prestige_gain\nadd_dread = minor_dread_gain\nadd_character_modifier = { modifier = eir_hill_war_modifier years = 3 }",
              "t443l", "The Norse hold the walls and throw you back", "add_prestige = medium_prestige_loss\nincrease_wounds_effect = { REASON = fight }", p=45, bonus=(20, "martial >= 14")),
         st=S_BRAVE, ai=35, ai_mod=[("brave", 20), ("wrathful", 15)]),
       O("Tax the camp's market and let it grow.",
         GAIN_M, "add_character_modifier = { modifier = eir_longphort_peace_modifier years = 6 }", PRESTIGE_S, "add_piety = minor_piety_loss",
         st=S_GREED, ai=35, ai_mod=[("greedy", 20)]),
       O("Send a spy to learn their numbers and their weakness.",
         "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 4 }", PRESTIGE_S, STRESS_UP,
         gate="OR = {\nintrigue >= 10\nhas_trait = deceitful\nhas_trait = shrewd\n}", st=S_DECEIT, ai=30, ai_mod=[("deceitful", 15), ("shrewd", 15)]),
       O("Offer the jarl the camp as a gift, if he swears to protect your coast.",
         "add_character_modifier = { modifier = eir_norse_kin_modifier years = 12 }", PRESTIGE_M, "add_piety = minor_piety_loss", "eir_vassal_opinion_effect = { MODIFIER = eir_norse_pact_opinion OPINION = -3 }",
         st=S_CYN, ai=15, ai_mod=[("cynical", 15)]),
   ],
   "war", gate=VIKING + "\nis_at_war = no", cooldown=15, immediate=PICK_NORSE, portraits=NORSE_P)

ev(444, "The Exchange of Hostages",
   "A Norse king proposes that each of you give the other a child to raise.",
   "It is how the Irish keep peace, and how the Norse keep peace, and for once the two peoples agree. A child of yours would go north to be raised in a hall full of axes and old songs. A child of his would come here, to be raised in a hall full of poets and ale. They would return in ten years, speaking each other's language.",
   [
       O("Send your own child.",
         "add_character_modifier = { modifier = eir_hostage_peace_modifier years = 10 }", PRESTIGE_M, "add_hook = { target = scope:eir_norse type = strong_hook }", STRESS_UP,
         gate="any_child = { is_adult = no is_alive = yes }", st="paranoid = minor_stress_impact_gain\ntrusting = minor_stress_impact_loss", ai=20, ai_mod=[("trusting", 25), ("ambitious", 10)]),
       O("Send a nephew, and keep your own close.",
         "add_character_modifier = { modifier = eir_hostage_peace_modifier years = 6 }", PRESTIGE_S, "scope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -8 } }",
         st=S_SHREWD, ai=40, ai_mod=[("shrewd", 15), ("paranoid", 10)]),
       O("Take his child, and send none.",
         "add_hook = { target = scope:eir_norse type = strong_hook }", PRESTIGE_S, "scope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -25 } }", "add_character_modifier = { modifier = eir_raider_infamy_modifier years = 4 }",
         st=S_DECEIT, ai=15, ai_mod=[("deceitful", 20), ("arrogant", 10)]),
       O("Refuse. An Irishman is not raised by pagans.",
         PIETY_M, PRESTIGE_S, "scope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -12 } }",
         st=S_ZEAL, ai=25, ai_mod=[("zealous", 20)]),
   ],
   "hostage", gate=VIKING + "\nis_at_war = no", cooldown=25, immediate=PICK_NORSE, portraits=NORSE_P)

ev(445, "The Apostle to the Norse",
   "A monk from your best monastery wants to go and convert the pagans of the harbour town.",
   "He is not a young man, and he is not a fool. He has spent three years learning the Norse tongue from a captive, and he says that its poetry is almost as good as Irish. He asks for a bell, a boat and a bishop's blessing. He does not ask for protection, which worries your steward.",
   [
       O("Send him with a bell, a boat and an escort.",
         GOLD_S, PIETY_L, "add_character_modifier = { modifier = eir_missionary_glory_modifier years = 5 }", xp("lifestyle_mystic", 20),
         st=S_ZEAL, ai=40, ai_mod=[("zealous", 25)]),
       O("Go with him yourself, for the first mile.",
         PIETY_M, PRESTIGE_M, xp("lifestyle_traveler", 20), "add_stress = minor_stress_gain", "eir_trait_effect = { TRAIT = zealous OPPOSITE = cynical CHANCE = 25 }",
         gate="piety >= 80", st=S_BRAVE, ai=20, ai_mod=[("brave", 15), ("zealous", 10)]),
       O("Fund him, but only if he reports what the Norse are planning.",
         GOLD_S, PIETY_S, "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 5 }", PRESTIGE_S,
         gate="OR = {\nintrigue >= 9\nhas_trait = shrewd\nhas_trait = deceitful\n}", st=S_SHREWD, ai=30, ai_mod=[("shrewd", 20)]),
       O("Refuse. The Norse will eat him alive.",
         "add_stress = miniscule_stress_gain", "add_piety = minor_piety_loss", st=S_CYN, ai=10, ai_mod=[("cynical", 15)]),
   ],
   "faith", gate=VIKING + "\npiety >= 50", cooldown=20)

ev(446, "Thor's Hammer on the Church Door",
   "A Norse hammer has been nailed to the door of a church, and the church has nailed a cross to the Norse hall.",
   "Nobody knows who started it. Both sides say the other did. A fight broke out at the market, a farmer's son was cut, and a pagan's boat was set adrift. The bishop wants blood. The Norse jarl wants an apology. You would like to eat your dinner.",
   [
       O("Hold a joint hearing before a brehon and the jarl's law-speaker.",
         PRESTIGE_M, "eir_trait_effect = { TRAIT = just OPPOSITE = arbitrary CHANCE = 30 }", "add_character_modifier = { modifier = eir_fair_lord_modifier years = 5 }", STRESS_UP,
         gate="OR = {\nlearning >= 9\nhas_trait = just\nhas_trait = patient\n}", st=S_PATIENT, ai=40, ai_mod=[("just", 20), ("patient", 15)]),
       O("Side with the Church, and fine the Norse.",
         PIETY_M, GAIN_S, "scope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -15 } }", PRESTIGE_S,
         st=S_ZEAL, ai=35, ai_mod=[("zealous", 25)]),
       O("Side with the Norse, and fine the Church.",
         GAIN_M, "add_piety = medium_piety_loss", "scope:eir_norse = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 25 } }",
         "eir_vassal_opinion_effect = { MODIFIER = eir_norse_pact_opinion OPINION = -4 }", st=S_CYN, ai=15, ai_mod=[("cynical", 25)]),
       O("Remove both from your land for a season.",
         "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", PRESTIGE_S, "add_stress = minor_stress_gain",
         st=S_PATIENT, ai=30),
   ],
   "faith", gate=VIKING, cooldown=15, immediate=PICK_NORSE)

ev(447, "The Norse Smith's Secret",
   "A Norse smith in the harbour town can weld iron the way no Irish smith can, and he is for sale.",
   "He has been banished by his own jarl for losing a bet. He has a pattern-welding technique that makes a sword spine flex and an edge stay sharp through a week of battle. He wants a forge, a wife and a guarantee that nobody will ask him to convert.",
   [
       O("Buy his contract and set him up in your finest forge.",
         GOLD_M, "eir_make_artifact_effect = { NAME = eir_norse_blade_name DESC = eir_norse_blade_desc TYPE = sword VISUALS = sword MODIFIER = eir_norse_blade_modifier }",
         PRESTIGE_S, xp("lifestyle_blademaster", 20), gate="gold >= 150", st=S_GREED, ai=40, ai_mod=[("greedy", 10), ("ambitious", 15)]),
       O("Steal his method and send him home.",
         luck("t447w", "You learn the secret", "add_character_modifier = { modifier = eir_norse_steel_modifier years = 12 }\nadd_prestige = minor_prestige_gain",
              "t447l", "He is not as stupid as he looks", "add_prestige = minor_prestige_loss\nadd_stress = minor_stress_gain", p=45, bonus=(25, "intrigue >= 14")),
         gate="OR = {\nintrigue >= 10\nhas_trait = deceitful\n}", st=S_DECEIT, ai=20, ai_mod=[("deceitful", 25)]),
       O("Let one of your own smiths apprentice with him.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_norse_steel_modifier years = 8 }", "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 3 }",
         st=S_PATIENT, ai=40, ai_mod=[("patient", 15), ("generous", 10)]),
       O("Refuse. A heathen smith is not welcome in a Christian hall.",
         PIETY_S, "eir_trait_effect = { TRAIT = zealous OPPOSITE = cynical CHANCE = 20 }", st=S_ZEAL, ai=15, ai_mod=[("zealous", 20)]),
   ],
   "stewardship", gate=VIKING + "\ngold >= 80", cooldown=25, immediate=PICK_NORSE)

ev(448, "Wolfhounds for the Jarl",
   "A Norse jarl wants a pair of Irish wolfhounds, and will pay a ship's worth for them.",
   "The Irish hound is taller than a pony and braver than most knights. The Norse think them magical. You have a litter of eight in the kennels, and three of them are the sort of animals poets compose odes to. The jarl's steward is polite and extremely persistent.",
   [
       O("Sell the two best for a king's price.",
         GAIN_M, "scope:eir_norse = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 20 } }", PRESTIGE_S, "add_hook = { target = scope:eir_norse type = favor_hook }",
         st=S_GREED, ai=40, ai_mod=[("greedy", 20)]),
       O("Give him a pair as a gift, to be remembered.",
         PRESTIGE_M, "scope:eir_norse = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }", "add_character_modifier = { modifier = eir_hospitality_modifier years = 5 }",
         st=S_GEN, ai=35, ai_mod=[("generous", 25)]),
       O("Refuse. They belong to the Gael.",
         "add_character_modifier = { modifier = eir_hunting_hounds_modifier years = 8 }", PRESTIGE_S, xp("lifestyle_hunter", 20),
         st=S_ARROG, ai=25, ai_mod=[("arrogant", 15), ("stubborn", 10)]),
       O("Sell him dogs that look fine and hunt badly.",
         GAIN_M, luck("t448w", "The jarl never finds out", "add_prestige = minor_prestige_gain",
                      "t448l", "The jarl's huntsman is no fool", "add_prestige = medium_prestige_loss\nscope:eir_norse = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -30 } }", p=50, bonus=(15, "intrigue >= 12")),
         gate="OR = {\nhas_trait = deceitful\nintrigue >= 10\n}", st=S_DECEIT, ai=15, ai_mod=[("deceitful", 25)]),
   ],
   "hunting", gate=VIKING, cooldown=20, immediate=PICK_NORSE, portraits=NORSE_P)

ev(449, "The Raiders' Hoard",
   "A farmer ploughing a stony field has turned up a pot of silver.",
   "It is Norse silver, hacksilver and coins and a half-finished brooch, buried by raiders who never came back for it. The farmer knows what it is. He has also heard that the law gives a finder's share. He is waiting at your gate with his cap in his hands and the pot behind his back.",
   [
       O("Honour the law: he gets a third, and the rest is yours.",
         GAIN_M, "eir_trait_effect = { TRAIT = just OPPOSITE = arbitrary CHANCE = 25 }", PRESTIGE_S, "eir_court_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = 2 }",
         st=S_HONEST, ai=40, ai_mod=[("just", 20), ("honest", 10)]),
       O("Take it all and send him away.",
         GAIN_M, "add_gold = minor_gold_value", "add_prestige = minor_prestige_loss", "eir_trait_effect = { TRAIT = arbitrary OPPOSITE = just CHANCE = 25 }",
         st=S_GREED, ai=20, ai_mod=[("greedy", 25), ("arbitrary", 15)]),
       O("Give it to the monastery and take nothing.",
         PIETY_L, PRESTIGE_S, "add_character_modifier = { modifier = eir_saints_blessing_modifier years = 4 }", st=S_ZEAL, ai=25, ai_mod=[("zealous", 25), ("generous", 10)]),
       O("Melt it down and make a cup for the high table.",
         PRESTIGE_M, "eir_make_artifact_effect = { NAME = eir_hoard_cup_name DESC = eir_hoard_cup_desc TYPE = goblet VISUALS = goblet MODIFIER = eir_hoard_cup_modifier }",
         gate=FILI, st=S_AMBIT, ai=30),
   ],
   "stewardship", gate="eir_viking_age_trigger = yes", cooldown=20)

ev(450, "The Sea-Wolf's Son",
   "A young man of mixed blood has come to your court, and he is asking for a place in your warband.",
   "His father was a Norse captain and his mother an Irish abbess's niece, which is a family story nobody has ever told in a straight line. He is tall and quiet, and he sits beside the smiths because he finds their conversation restful. He says he fights with both hands and prays with neither.",
   [
       O("Give him a place among your household guard.",
         "add_character_modifier = { modifier = eir_norse_kin_modifier years = 8 }", PRESTIGE_S, "add_character_modifier = { modifier = eir_gallowglass_paymaster_modifier years = 6 }",
         st=S_GEN, ai=40, ai_mod=[("generous", 15), ("trusting", 10)]),
       O("Test his courage in a single combat.",
         luck("t450w", "He wins, and you admire him", "add_prestige = minor_prestige_gain\nadd_character_modifier = { modifier = eir_norse_kin_modifier years = 10 }\nadd_trait_xp = { trait = lifestyle_blademaster value = 20 }",
              "t450l", "He loses badly, and so do you in the eyes of the hall", "add_prestige = minor_prestige_loss\nincrease_wounds_effect = { REASON = fight }", p=55, bonus=(20, "prowess >= 14")),
         gate="OR = {\nprowess >= 12\nhas_trait = brave\n}", st=S_BRAVE, ai=30, ai_mod=[("brave", 20)]),
       O("Send him to the monastery to be educated.",
         PIETY_S, "add_character_modifier = { modifier = eir_hospitality_modifier years = 5 }", PRESTIGE_S, st=S_ZEAL, ai=30, ai_mod=[("zealous", 15)]),
       O("Send him away. His loyalty is divided.",
         "add_stress = miniscule_stress_gain", "add_character_modifier = { modifier = eir_raider_infamy_modifier years = 3 }", st=S_CYN, ai=15, ai_mod=[("paranoid", 20)]),
   ],
   "court", gate=VIKING + "\nexists = capital_province", cooldown=20)

ev(451, "The Dark Foreigners and the Fair Foreigners",
   "Two Norse kings are fighting each other over the harbour of a river-mouth, and each has asked for your help.",
   "The poets call them the Dubh Gaill and the Finn Gaill, the dark and the fair foreigners, and nobody remembers which is which. They hold different bays, speak different dialects and hate each other with the energy of long acquaintance. This is the first time in a generation that they have not been united against someone else.",
   [
       O("Back the larger, and take a share of the spoils.",
         GAIN_M, PRESTIGE_S, "add_character_modifier = { modifier = eir_norse_spoils_modifier years = 4 }", "add_hook = { target = scope:eir_norse type = favor_hook }",
         st=S_GREED, ai=35, ai_mod=[("greedy", 15), ("ambitious", 10)]),
       O("Back the smaller, and make a friend.",
         PRESTIGE_M, "scope:eir_norse = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 30 } }", "add_character_modifier = { modifier = eir_norse_kin_modifier years = 8 }",
         st=S_GEN, ai=25, ai_mod=[("generous", 15), ("humble", 10)]),
       O("Back neither, and sell them both arms.",
         GAIN_M, "add_character_modifier = { modifier = eir_irish_sea_trade_modifier years = 4 }", "add_piety = minor_piety_loss",
         st=S_GREED, ai=25, ai_mod=[("greedy", 20), ("shrewd", 10)]),
       O("Let them fight, and strike the winner while he is weak.",
         "add_character_flag = { flag = eir_oath_to_reclaim years = 10 }", "eir_grant_claims_norse_effect = yes", PRESTIGE_S,
         gate="eir_stage2_trigger = yes", st=S_DECEIT, ai=30, ai_mod=[("ambitious", 20), ("deceitful", 15)]),
   ],
   "war", gate=VIKING + "\neir_stage1_trigger = yes", cooldown=25, immediate=PICK_NORSE, portraits=NORSE_P)

ev(452, "The Tribute of the Ostmen",
   "The Norse townsmen of your harbour have refused to pay the king's share.",
   "They say the old agreement was with your father, and your father is dead. They say they are free traders and that the harbour belongs to nobody. They have sent a delegation with an offer: a smaller sum, paid in silver, with no questions asked. It is quite a decent offer.",
   [
       O("Accept the smaller sum.",
         GAIN_M, "add_character_modifier = { modifier = eir_longphort_peace_modifier years = 5 }", STRESS_DOWN, st=S_CONTENT, ai=35, ai_mod=[("content", 15), ("patient", 10)]),
       O("Insist on the old agreement, with a company at your back.",
         GAIN_M, "add_dread = minor_dread_gain", "capital_county ?= { add_county_modifier = { modifier = eir_ostmen_quarter_modifier years = 5 } }", STRESS_UP,
         st=S_HARD, ai=30, ai_mod=[("callous", 15), ("wrathful", 10)]),
       O("Offer them a seat on your council in exchange.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_fair_lord_modifier years = 6 }", "capital_county ?= { add_county_modifier = { modifier = eir_ostmen_quarter_modifier years = 15 } }",
         gate="diplomacy >= 9", st=S_FORGIVE, ai=35, ai_mod=[("forgiving", 15), ("gregarious", 10)]),
       O("Expel them from the harbour.",
         "add_dread = medium_dread_gain", PRESTIGE_S, "eir_raid_county_effect = yes", "eir_trait_effect = { TRAIT = wrathful OPPOSITE = patient CHANCE = 20 }",
         st=S_WRATH, ai=15, ai_mod=[("wrathful", 20), ("sadistic", 15)]),
   ],
   "stewardship", gate="eir_holds_norse_county_trigger = yes", cooldown=15)

ev(453, "The Bell That Rang Too Late",
   "The bell of a coastal monastery was cracked a year ago, and nobody has had the money to cast a new one.",
   "On the day the Norse came, the monks rang what they had. The note carried a hundred yards and then died. Nobody heard it. They have been trying to explain to you for months that a bell is not decoration: it is the only warning a coastal village has.",
   [
       O("Pay for a new bell, and a better tower.",
         GOLD_M, PIETY_M, "capital_county ?= { add_county_modifier = { modifier = eir_beacon_county_modifier years = 10 } }", PRESTIGE_S,
         gate="gold >= 120", st=S_GEN, ai=40, ai_mod=[("generous", 15), ("zealous", 15)]),
       O("Melt down the old plate of three churches to cast one.",
         PIETY_S, "add_character_modifier = { modifier = eir_beacons_modifier years = 5 }", "eir_vassal_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = -2 }",
         st=S_SHREWD, ai=30, ai_mod=[("shrewd", 15)]),
       O("Order a beacon on every headland instead.",
         GOLD_S, "every_realm_county = {\n\tlimit = { is_coastal_county = yes }\n\tadd_county_modifier = { modifier = eir_beacon_county_modifier years = 8 }\n}", PRESTIGE_S,
         st=S_SHREWD, ai=35, ai_mod=[("diligent", 15)]),
       O("Pray over the cracked bell and hope.",
         PIETY_M, "add_stress = minor_stress_gain", st=S_ZEAL, ai=10, ai_mod=[("zealous", 15)]),
   ],
   "faith", gate="eir_viking_age_trigger = yes\neir_has_coast_trigger = yes\npiety >= 40", cooldown=20)

# =============================================================================
# GAELS AGAINST GAELS
# =============================================================================
ev(456, "The Cattle Raid Across the Boundary",
   "A band of young men from a neighbouring kingdom has driven off three hundred head of your cattle.",
   "It is, strictly speaking, not a raid: it is a custom. A young man proves himself by taking cattle from the next kingdom, and the next kingdom proves itself by taking them back. The trouble is that three hundred head is more than a custom. The trouble is also that your cousins are in the herd.",
   [
       O("Ride after them with your household.",
         luck("t456w", "You recover the cattle and a prisoner", "add_gold = minor_gold_value\nadd_prestige = medium_prestige_gain\nadd_trait_xp = { trait = lifestyle_hunter value = 20 }",
              "t456l", "They are over the border before you reach them", "add_prestige = minor_prestige_loss\nadd_stress = minor_stress_gain", p=55, bonus=(15, "martial >= 12")),
         st=S_BRAVE, ai=40, ai_mod=[("brave", 20), ("wrathful", 10)]),
       O("Send a poet to the other king with a verse of complaint.",
         PRESTIGE_S, xp("lifestyle_poet", 20), "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -10 } }",
         luck("t456m", "The shamed king returns half", "add_gold = minor_gold_value\nadd_prestige = minor_prestige_gain", "t456n", "The poet is thrown out", "add_prestige = minor_prestige_loss", p=50),
         gate=FILI, st=S_HUMBLE, ai=30),
       O("Raid back, bigger.",
         GAIN_M, "add_dread = minor_dread_gain", "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -25 } }", PRESTIGE_S,
         "add_character_flag = { flag = eir_vowed_vengeance years = 5 }", st=S_WRATH, ai=30, ai_mod=[("wrathful", 25), ("vengeful", 20)]),
       O("Pay the cattle-price in law, and take it to the brehon.",
         "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 20 } }", PRESTIGE_M, "add_character_modifier = { modifier = eir_fair_lord_modifier years = 5 }", STRESS_UP,
         gate="has_global_variable = eir_unlock_brehon_court", st=S_PATIENT, ai=30, ai_mod=[("just", 20)]),
   ],
   "war", gate=RIVAL_ANY, cooldown=12, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(457, "A Blinded Cousin",
   "Your cousin has come to your hall with his eyes bound, and he does not want to say who did it.",
   "In the old law, a man who is blind or maimed cannot be king. Someone has made sure of that. He sits by the fire and holds a harp he cannot see. His claim to the line was as good as yours.\n\nHe has asked for nothing. That is what worries you.",
   [
       O("Swear to find whoever did this.",
         "add_character_flag = { flag = eir_vowed_vengeance years = 8 }", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = 4 }", "add_character_modifier = { modifier = eir_kin_defended_modifier years = 8 }",
         st=S_WRATH, ai=35, ai_mod=[("vengeful", 25), ("just", 15)]),
       O("Make him your poet and keep him close.",
         PRESTIGE_S, xp("lifestyle_poet", 20), "add_character_modifier = { modifier = eir_bardic_circuit_modifier years = 6 }", "eir_trait_effect = { TRAIT = compassionate OPPOSITE = callous CHANCE = 25 }",
         st=S_KIND, ai=40, ai_mod=[("compassionate", 25)]),
       O("Question him quietly, and learn who benefits.",
         "add_character_modifier = { modifier = eir_foreknowledge_modifier years = 4 }", PRESTIGE_S, STRESS_UP,
         gate="OR = {\nintrigue >= 10\nhas_trait = shrewd\n}", st=S_SHREWD, ai=30, ai_mod=[("shrewd", 20)]),
       O("Send him to a monastery, where he will be safe.",
         PIETY_M, "add_character_modifier = { modifier = eir_hospitality_modifier years = 4 }", "add_stress = miniscule_stress_gain", st=S_ZEAL, ai=25, ai_mod=[("zealous", 15)]),
   ],
   "family", gate="eir_collapse_active_trigger = yes", cooldown=25)

ev(458, "The Poet's Satire",
   "A famous poet has composed a satire on you, and it is already being recited in every hall.",
   "It begins well, with an invocation, and ends in a list of your failings that rhymes in four ways. The worst of it is that it is accurate. The Irish believe a satire raises blisters on the face of its target. Yours has not yet, but your steward has started to look at you strangely.",
   [
       O("Pay the poet well, and ask for a better verse.",
         GOLD_M, "eir_court_opinion_effect = { MODIFIER = eir_poet_praise_opinion OPINION = 6 }", PRESTIGE_S, "add_character_modifier = { modifier = eir_honour_restored_modifier years = 4 }",
         st=S_GEN, ai=40, ai_mod=[("generous", 20), ("humble", 10)]),
       O("Answer him with a satire of your own.",
         luck("t458w", "Your verse is better", "add_prestige = medium_prestige_gain\nadd_trait_xp = { trait = lifestyle_poet value = 30 }",
              "t458l", "Your verse is worse, and everyone says so", "add_prestige = medium_prestige_loss\nadd_stress = minor_stress_gain", p=45, bonus=(25, "learning >= 14")),
         gate="learning >= 9", st=S_ARROG, ai=25, ai_mod=[("arrogant", 20), ("wrathful", 10)]),
       O("Laugh it off in front of the court.",
         PRESTIGE_S, STRESS_DOWN, "eir_trait_effect = { TRAIT = calm OPPOSITE = wrathful CHANCE = 25 }", gate="OR = {\nhas_trait = calm\nhas_trait = patient\nhas_trait = humble\n}",
         st=S_PATIENT, ai=35, ai_mod=[("calm", 20), ("humble", 15)]),
       O("Banish the poet from your kingdom.",
         "add_dread = minor_dread_gain", "add_piety = minor_piety_loss", LOSS_S, "eir_trait_effect = { TRAIT = wrathful OPPOSITE = patient CHANCE = 25 }",
         st=S_WRATH, ai=15, ai_mod=[("wrathful", 25), ("arrogant", 15)]),
   ],
   "court", gate=FILI, cooldown=20)

ev(459, "The Quarrel of the Two Septs",
   "Two branches of the same dynasty are at each other's throats over a hill, and each says you promised it to them.",
   "You did, in fact, promise it to both. It had seemed a convenient thing to say at the time. Now they are standing on opposite sides of the hall with their hands on their knives, and the brehon is quietly looking for the door.",
   [
       O("Judge the case on the law and the genealogy.",
         luck("t459w", "Both sides accept the judgement", "add_prestige = medium_prestige_gain\nadd_character_modifier = { modifier = eir_fair_lord_modifier years = 6 }\neir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = 5 }",
              "t459l", "Neither accepts, and both leave in a temper", "add_prestige = minor_prestige_loss\neir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = -4 }", p=55, bonus=(20, "learning >= 12")),
         gate="OR = {\nlearning >= 9\nhas_trait = just\n}", st=S_PATIENT, ai=40, ai_mod=[("just", 20)]),
       O("Split the hill between them.",
         PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = 2 }", "add_character_modifier = { modifier = eir_wergild_peace_modifier years = 5 }",
         st=S_FORGIVE, ai=40, ai_mod=[("patient", 10)]),
       O("Give it to the stronger branch, and watch the weaker.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = -3 }", "add_hook = { target = scope:eir_rival type = favor_hook }",
         st=S_HARD, ai=20, ai_mod=[("callous", 15), ("ambitious", 10)]),
       O("Give it to the Church to settle.",
         PIETY_M, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 5 }", "eir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = -1 }",
         st=S_ZEAL, ai=30, ai_mod=[("zealous", 15), ("humble", 10)]),
   ],
   "vassal", gate="any_vassal = { is_adult = yes }", cooldown=15, immediate="random_vassal = {\n\tlimit = { is_adult = yes }\n\tsave_scope_as = eir_rival\n}", portraits=RIVAL_P)

ev(460, "A King Without a Hall",
   "An exiled king has come to your gate with forty men and no cattle.",
   "He is the rightful king of a province two days' ride away, he says, and his cousin took the hall while he was at the funeral of their grandfather. He asks nothing but a bed. A guest is sacred. But he is also a claim, and a claim is a weapon, and weapons have owners.",
   [
       O("Shelter him as a guest, and ask nothing in return.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_hospitality_modifier years = 8 }", "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }", xp("lifestyle_reveler", 15),
         st=S_GEN, ai=40, ai_mod=[("generous", 20), ("compassionate", 15)]),
       O("Shelter him, and make him swear fealty.",
         "add_hook = { target = scope:eir_rival type = strong_hook }", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = -2 }",
         st=S_AMBIT, ai=30, ai_mod=[("ambitious", 20), ("shrewd", 10)]),
       O("Back his claim with your spears.",
         "add_character_flag = { flag = eir_oath_to_reclaim years = 10 }", PRESTIGE_M, "add_character_modifier = { modifier = eir_kin_defended_modifier years = 6 }", GAIN_S,
         gate="eir_stage1_trigger = yes", st=S_BRAVE, ai=20, ai_mod=[("brave", 15), ("just", 10)]),
       O("Send him on to the next king.",
         "add_stress = miniscule_stress_gain", "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -8 } }", st=S_CYN, ai=15, ai_mod=[("craven", 15)]),
   ],
   "court", gate=RIVAL_ANY, cooldown=15, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(461, "Fosterage Betrayed",
   "Your foster-son has joined your enemies, and he took your best horse.",
   "You raised him as your own. You taught him to ride, to throw a spear, to compose a verse and to keep his word. He kept three of the four. He says he is sorry and he says his father's claim is just. He says you will understand some day.",
   [
       O("Forgive him in public and ask him to return.",
         PRESTIGE_M, "eir_trait_effect = { TRAIT = forgiving OPPOSITE = vengeful CHANCE = 30 }", "add_character_modifier = { modifier = eir_foster_bond_modifier years = 12 }", STRESS_UP,
         gate="OR = {\nhas_trait = forgiving\nhas_trait = compassionate\nhas_trait = patient\n}", st=S_FORGIVE, ai=30, ai_mod=[("forgiving", 25)]),
       O("Hunt him down and bring him back in chains.",
         luck("t461w", "He is taken alive", "add_prestige = minor_prestige_gain\nadd_dread = minor_dread_gain\nadd_character_modifier = { modifier = eir_hostage_peace_modifier years = 5 }",
              "t461l", "He escapes into the next kingdom", "add_prestige = minor_prestige_loss\nadd_stress = minor_stress_gain", p=45, bonus=(15, "martial >= 12")),
         st=S_WRATH, ai=30, ai_mod=[("vengeful", 20), ("wrathful", 15)]),
       O("Write him out of the poems and the genealogy.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "add_character_modifier = { modifier = eir_kin_distrust_modifier years = 6 }", STRESS_DOWN,
         st=S_HARD, ai=35, ai_mod=[("callous", 15), ("vengeful", 10)]),
       O("Let him go. Love is not a hostage.",
         PRESTIGE_S, "eir_trait_effect = { TRAIT = compassionate OPPOSITE = callous CHANCE = 25 }", STRESS_DOWN, "add_character_modifier = { modifier = eir_foster_bond_modifier years = 5 }",
         st=S_KIND, ai=30, ai_mod=[("compassionate", 20)]),
   ],
   "family", gate=FOSTER, cooldown=30)

ev(462, "The Moved Boundary Stone",
   "An ogham stone on the border has been moved forty paces to the east.",
   "The notches on the stone name the boundary of your kingdom, and the farmers have farmed to it for a century. Now the stone stands in a field that used to be yours. Nobody saw it moved. A neighbour's herdsman says he heard thunder, and a stone is a heavy thing for thunder to carry.",
   [
       O("Order the stone returned, with a company to guard it.",
         "add_dread = minor_dread_gain", PRESTIGE_S, "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -12 } }",
         "capital_county ?= { add_county_modifier = { modifier = eir_ogham_boundary_modifier years = 10 } }", st=S_BRAVE, ai=35, ai_mod=[("brave", 15), ("stubborn", 10)]),
       O("Summon the brehons to walk the boundary.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_fair_lord_modifier years = 5 }", "capital_county ?= { add_county_modifier = { modifier = eir_ogham_boundary_modifier years = 15 } }",
         gate="has_global_variable = eir_unlock_brehon_court", st=S_PATIENT, ai=40, ai_mod=[("just", 20), ("patient", 15)]),
       O("Move one of his stones forty paces west in return.",
         luck("t462w", "Nobody notices for a year", "add_gold = minor_gold_value\nadd_prestige = minor_prestige_gain",
              "t462l", "He notices at once", "add_prestige = minor_prestige_loss\nscope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -30 } }", p=50, bonus=(20, "intrigue >= 12")),
         st=S_DECEIT, ai=20, ai_mod=[("deceitful", 25)]),
       O("Let it be. A stone is only a stone.",
         STRESS_DOWN, "add_prestige = minor_prestige_loss", "add_character_modifier = { modifier = eir_hospitality_modifier years = 3 }", st=S_CONTENT, ai=15, ai_mod=[("content", 20)]),
   ],
   "vassal", gate=RIVAL_ANY, cooldown=15, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(463, "The Contest for the Kingship",
   "Two cousins are contesting the kingship of a neighbouring province, and both want your blessing.",
   "One is old and popular and has been disliked by his own sons. The other is young and competent and has been disliked by everyone else. The poets have composed a verse for each. The verse for the young one is better. A king's blessing is worth three hundred spears.",
   [
       O("Back the old king.",
         PRESTIGE_S, "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 30 } }", "add_hook = { target = scope:eir_rival type = favor_hook }", PIETY_S,
         st=S_PATIENT, ai=35, ai_mod=[("content", 15), ("just", 10)]),
       O("Back the young claimant.",
         PRESTIGE_M, "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 20 } }", "add_character_modifier = { modifier = eir_kingmaker_modifier years = 8 }", STRESS_UP,
         st=S_AMBIT, ai=35, ai_mod=[("ambitious", 25)]),
       O("Arrange a single combat to decide it.",
         PRESTIGE_M, luck("t463w", "The challenger wins, and your reputation grows", "add_prestige = minor_prestige_gain\nadd_character_modifier = { modifier = eir_kingmaker_modifier years = 5 }",
                          "t463l", "The old king wins and resents the idea", "add_prestige = minor_prestige_loss", p=50),
         st=S_BRAVE, ai=20, ai_mod=[("brave", 15)]),
       O("Stay out of it, and sell both of them arms.",
         GAIN_M, "add_piety = minor_piety_loss", "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -8 } }",
         st=S_GREED, ai=30, ai_mod=[("greedy", 20)]),
   ],
   "vassal", gate=RIVAL_ANY, cooldown=20, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(464, "The Feast That Ended in Blood",
   "At a wedding feast in a neighbouring hall, the host's brother drew his knife.",
   "It was a great feast and everyone was there. The ale was strong, the poets were good, and the old grievance was bound to come up. When it did, it came up with a knife. Six men are dead and the king's sister is a widow. The survivors have sent for you as a neutral party. This is the first time anyone has called you neutral.",
   [
       O("Preside over the funeral and the settlement.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_fair_lord_modifier years = 6 }", "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 20 } }", xp("lifestyle_reveler", 15),
         gate="diplomacy >= 9", st=S_PATIENT, ai=40, ai_mod=[("calm", 15), ("just", 15)]),
       O("Take the widow under your protection.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_hospitality_modifier years = 6 }", "eir_trait_effect = { TRAIT = compassionate OPPOSITE = callous CHANCE = 25 }", "add_hook = { target = scope:eir_rival type = favor_hook }",
         st=S_KIND, ai=35, ai_mod=[("compassionate", 20)]),
       O("Demand the knife-bearer for justice.",
         PRESTIGE_S, "add_dread = minor_dread_gain", "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -10 } }", "eir_trait_effect = { TRAIT = just OPPOSITE = arbitrary CHANCE = 20 }",
         st=S_HARD, ai=30, ai_mod=[("just", 20), ("wrathful", 10)]),
       O("Stay away. Blood feuds are catching.",
         STRESS_DOWN, "add_prestige = minor_prestige_loss", st=S_CRAVEN, ai=20, ai_mod=[("craven", 20), ("paranoid", 10)]),
   ],
   "party", gate=RIVAL_ANY, cooldown=20, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(465, "A Cadet Branch Demands Land",
   "A younger branch of your dynasty wants a county of its own, and says the law is on its side.",
   "The Irish dynastic law is generous and exact: any man whose great-grandfather was a king may call himself a prince. Whether he gets a county is another matter. The branch has a genealogist, a poet and a lawyer, in that order. They have also, quietly, a hundred armed men.",
   [
       O("Grant them a county, and bind them to you.",
         "add_character_modifier = { modifier = eir_derbfine_counsel_modifier years = 8 }", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_justice_done_opinion OPINION = -2 }", GOLD_S,
         gate="any_held_title = { tier = tier_county }", st=S_GEN, ai=35, ai_mod=[("generous", 20)]),
       O("Offer them a place in the line of succession instead.",
         "add_character_modifier = { modifier = eir_tanaiste_modifier years = 8 }", PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_oath_sworn_opinion OPINION = 4 }",
         gate="eir_collapse_active_trigger = yes", st=S_PATIENT, ai=30, ai_mod=[("shrewd", 10)]),
       O("Deny them, and cite the law.",
         PRESTIGE_S, "add_character_modifier = { modifier = eir_kin_distrust_modifier years = 6 }", STRESS_UP,
         st=S_ARROG, ai=30, ai_mod=[("arrogant", 15), ("stubborn", 15)]),
       O("Send them to win land abroad.",
         PRESTIGE_M, "add_character_flag = { flag = eir_oath_to_reclaim years = 8 }", "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 3 }",
         gate="eir_has_celtic_britain_counties_trigger = yes", st=S_AMBIT, ai=40, ai_mod=[("ambitious", 20)]),
   ],
   "vassal", gate="eir_stage1_trigger = yes", cooldown=20)

ev(466, "A Challenge at the Ford",
   "A famous champion of a rival king has ridden to the ford and shouted your name.",
   "The old style: one man on each bank, shouting insults across the water until one of them cannot bear it. He has a reputation. He has killed nine men at fords and he claims that the tenth will be you. Your household has gone very quiet. The ford is wide and the water is cold.",
   [
       O("Ride out and meet him.",
         luck("t466w", "You win, and the story grows with each telling", "add_prestige = major_prestige_gain\nadd_trait_xp = { trait = lifestyle_blademaster value = 50 }\nadd_character_modifier = { modifier = eir_war_poem_modifier years = 5 }",
              "t466l", "You lose, and are carried home on your shield", "add_prestige = medium_prestige_loss\nincrease_wounds_effect = { REASON = fight }\nadd_stress = medium_stress_gain", p=45, bonus=(35, "prowess >= 18")),
         gate="OR = {\nprowess >= 12\nhas_trait = brave\n}", st=S_BRAVE, ai=30, ai_mod=[("brave", 25), ("wrathful", 10)]),
       O("Send your best champion in your place.",
         luck("t466m", "Your champion wins", "add_prestige = medium_prestige_gain\nadd_character_modifier = { modifier = eir_war_poem_modifier years = 3 }",
              "t466n", "Your champion falls", "add_prestige = minor_prestige_loss\nadd_stress = minor_stress_gain", p=50, bonus=(20, "martial >= 14")),
         st=S_SHREWD, ai=40, ai_mod=[("shrewd", 15)]),
       O("Answer in verse and let the poets decide.",
         PRESTIGE_S, xp("lifestyle_poet", 25), luck("t466p", "The poets declare you the better man", "add_prestige = medium_prestige_gain", "t466q", "The poets laugh", "add_prestige = minor_prestige_loss", p=50, bonus=(25, "learning >= 14")),
         gate="learning >= 9", st=S_HUMBLE, ai=25),
       O("Ignore him. A man is not obliged to fight on demand.",
         STRESS_UP, "add_prestige = medium_prestige_loss", "eir_trait_effect = { TRAIT = craven OPPOSITE = brave CHANCE = 20 }", st=S_CRAVEN, ai=10, ai_mod=[("craven", 25)]),
   ],
   "martial", gate=RIVAL_ANY, cooldown=20, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(467, "The Abbot Who Wanted a Kingdom",
   "The coarb of a great monastery has begun to raise tolls and call out spears, and the monks are carrying swords.",
   "In Ireland a monastery is a city, and the abbot is a lord. This one has a hundred monks, a thousand tenants, three high crosses and an ambition. He has also, without asking, begun to collect the king's share. His letters are written in perfect Latin and end with a blessing that sounds suspiciously like a threat.",
   [
       O("Negotiate a partition: the abbot takes the church lands, you take the rest.",
         PRESTIGE_S, PIETY_S, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 8 }", STRESS_UP,
         gate="diplomacy >= 9", st=S_PATIENT, ai=40, ai_mod=[("patient", 15), ("calm", 10)]),
       O("Excommunicate the abbot by appealing to the bishop.",
         PIETY_M, "add_character_modifier = { modifier = eir_heresy_hunter_modifier years = 6 }", "eir_vassal_opinion_effect = { MODIFIER = eir_hospitality_opinion OPINION = -3 }",
         gate="piety >= 120", st=S_ZEAL, ai=25, ai_mod=[("zealous", 20)]),
       O("March on the monastery and take the tolls by force.",
         "add_dread = minor_dread_gain", GAIN_M, "add_piety = medium_piety_loss", "eir_raid_county_effect = yes",
         st=S_HARD, ai=20, ai_mod=[("callous", 15), ("wrathful", 10)]),
       O("Make the abbot your chancellor and give him a say in the realm.",
         "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 12 }", PRESTIGE_S, GOLD_S, "eir_trait_effect = { TRAIT = shrewd OPPOSITE = trusting CHANCE = 20 }",
         st=S_SHREWD, ai=35, ai_mod=[("shrewd", 20), ("ambitious", 10)]),
   ],
   "faith", gate="piety >= 80\neir_stage1_trigger = yes", cooldown=25)

ev(468, "A Marriage Between Rivals",
   "Your daughter and the heir of your worst enemy have been seen walking together, more than once.",
   "She says it is entirely innocent. The heir says it is entirely innocent. The harper says that the song they are both humming is not an innocent song. The two kingdoms have been at each other's throats for sixty years. Someone, at some point, will have to marry someone.",
   [
       O("Bless the match, and call a peace feast.",
         PRESTIGE_M, "add_character_modifier = { modifier = eir_wergild_peace_modifier years = 10 }", "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }", xp("lifestyle_reveler", 20),
         gate="OR = {\nhas_trait = forgiving\nhas_trait = gregarious\ndiplomacy >= 11\n}", st=S_FORGIVE, ai=35, ai_mod=[("forgiving", 20), ("gregarious", 10)]),
       O("Allow it, but insist on large concessions.",
         GAIN_M, PRESTIGE_S, "add_hook = { target = scope:eir_rival type = strong_hook }", st=S_GREED, ai=30, ai_mod=[("greedy", 15), ("shrewd", 10)]),
       O("Forbid it, and send her to the nuns.",
         PIETY_S, "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -20 } }", "add_stress = minor_stress_gain",
         st=S_HARD, ai=20, ai_mod=[("stubborn", 20), ("vengeful", 15)]),
       O("Use the romance as a lever for a better deal.",
         luck("t468w", "The rival agrees to a hard bargain", "add_prestige = medium_prestige_gain\nadd_hook = { target = scope:eir_rival type = strong_hook }",
              "t468l", "The rival sees through it and withdraws", "add_prestige = minor_prestige_loss", p=50, bonus=(20, "intrigue >= 12")),
         st=S_DECEIT, ai=25, ai_mod=[("deceitful", 20)]),
   ],
   "marriage", gate=RIVAL_ANY + "\nany_child = { is_adult = yes is_female = yes }", cooldown=25, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(469, "The Winter Hosting",
   "A hosting of the young men of the province has gone out in the snow, and it is not going well.",
   "It was meant to be a short raid, a few cattle, a bit of glory before the thaw. Instead it has become a long march through a snowstorm with no supplies and a growing suspicion that the guide was bribed. The men are cold, the horses are dying, and your cousin the captain has not been seen for a day.",
   [
       O("Ride out yourself and bring them home.",
         luck("t469w", "You bring most of them back", "add_prestige = medium_prestige_gain\nadd_trait_xp = { trait = lifestyle_hunter value = 30 }\neir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 5 }",
              "t469l", "You find them frozen in a ravine", "add_prestige = minor_prestige_loss\nadd_stress = medium_stress_gain\neir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = -5 }", p=50, bonus=(25, "has_trait = lifestyle_hunter")),
         st=S_BRAVE, ai=35, ai_mod=[("brave", 20)]),
       O("Send supplies and a sledge party under your steward.",
         GOLD_M, PRESTIGE_S, "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = 3 }", gate="gold >= 120", st=S_SHREWD, ai=35, ai_mod=[("diligent", 10)]),
       O("Pray, and hold a vigil in the hall.",
         PIETY_M, "add_character_modifier = { modifier = eir_saints_blessing_modifier years = 3 }", "add_stress = minor_stress_gain",
         st=S_ZEAL, ai=20, ai_mod=[("zealous", 20)]),
       O("Do nothing. They were fools to go.",
         STRESS_DOWN, "eir_vassal_opinion_effect = { MODIFIER = eir_hosting_opinion OPINION = -4 }", "add_prestige = minor_prestige_loss",
         st=S_HARD, ai=15, ai_mod=[("callous", 20), ("lazy", 10)]),
   ],
   "martial", gate="eir_stage1_trigger = yes", cooldown=15)

ev(470, "The Hostage Escapes",
   "A hostage you were keeping has slipped his guards and fled across the border.",
   "He was a boy of twelve, the son of a vassal you did not trust. He went through the privy and over the wall in the dark, and the dogs lost him at the river. He will be home by morning. His father will not be pleased with how he was kept, and the boy has a good memory.",
   [
       O("Send riders after him at once.",
         luck("t470w", "He is caught before he reaches the border", "add_prestige = minor_prestige_gain\nadd_dread = minor_dread_gain",
              "t470l", "He reaches his father", "add_prestige = minor_prestige_loss\neir_vassal_opinion_effect = { MODIFIER = eir_hard_justice_opinion OPINION = -3 }", p=50, bonus=(15, "martial >= 10")),
         st=S_HARD, ai=35, ai_mod=[("callous", 10), ("wrathful", 10)]),
       O("Let him go, and send a message of goodwill.",
         PRESTIGE_S, "eir_trait_effect = { TRAIT = compassionate OPPOSITE = callous CHANCE = 25 }", "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 25 } }",
         st=S_KIND, ai=30, ai_mod=[("compassionate", 20)]),
       O("Punish the guards, and double the watch.",
         "add_dread = minor_dread_gain", "eir_court_opinion_effect = { MODIFIER = eir_hard_justice_opinion OPINION = -3 }", GOLD_S,
         st=S_HARD, ai=30, ai_mod=[("callous", 15)]),
       O("Admit the failure openly.",
         PRESTIGE_S, "eir_trait_effect = { TRAIT = honest OPPOSITE = deceitful CHANCE = 25 }", "add_character_modifier = { modifier = eir_honour_restored_modifier years = 3 }",
         st=S_HONEST, ai=25, ai_mod=[("honest", 25)]),
   ],
   "hostage", gate="eir_stage1_trigger = yes\nhas_global_variable = eir_done_oenach", cooldown=20, immediate=PICK_RIVAL, portraits=RIVAL_P)

ev(471, "A Treaty Sworn on the Relics",
   "A rival king proposes a peace sworn on the relics of a saint, and he wants it witnessed by the bishops of three provinces.",
   "It is the oldest of Irish diplomacy: the oath on the bones. A king who breaks it is damned in this world and the next, and every poet in Ireland writes verses about him. A king who keeps it is remembered. The rival king is not sentimental. He just does not want to fight you this year.",
   [
       O("Swear the peace and mean it.",
         PIETY_M, PRESTIGE_M, "add_character_modifier = { modifier = eir_peace_with_church_modifier years = 8 }", "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 40 } }",
         gate="piety >= 60", st=S_HONEST, ai=40, ai_mod=[("honest", 20), ("zealous", 15)]),
       O("Swear it, but keep the right to break it in a pinch.",
         PIETY_S, "add_character_modifier = { modifier = eir_raider_infamy_modifier years = 5 }", PRESTIGE_S, "scope:eir_rival = { add_opinion = { target = root modifier = eir_fair_dealing_opinion opinion = 15 } }",
         st=S_DECEIT, ai=20, ai_mod=[("deceitful", 25)]),
       O("Refuse to swear on a saint's bones for a king's convenience.",
         PIETY_S, PRESTIGE_S, "scope:eir_rival = { add_opinion = { target = root modifier = eir_slighted_envoy_opinion opinion = -8 } }", st=S_ARROG, ai=20, ai_mod=[("arrogant", 15)]),
       O("Offer an alliance instead of a peace.",
         PRESTIGE_M, "add_hook = { target = scope:eir_rival type = favor_hook }", "add_character_modifier = { modifier = eir_wergild_peace_modifier years = 6 }",
         gate="eir_stage2_trigger = yes", st=S_AMBIT, ai=30, ai_mod=[("ambitious", 15), ("gregarious", 10)]),
   ],
   "faith", gate=RIVAL_ANY + "\nis_at_war = no", cooldown=20, immediate=PICK_RIVAL, portraits=RIVAL_P)
