"""Hand-style script for Update 2 content, generated so the repetitive parts (three Black Host waves, four size tiers)
cannot drift apart. Writes (all with BOM):
  common/scripted_effects/eir_effects_v8.txt
  common/scripted_triggers/eir_triggers3.txt
  common/on_action/eir_on_actions_v8.txt
"""
from eir_lib import *

# (levies, light_footmen, armored_footmen, huscarl, skirmishers) per realm-size tier: <4, 4-9, 10-19, 20+ counties
WAVES = {
    1: dict(name="eir_bh_wave1_name", levies=(2200, 3200, 4500, 6500), light=(3, 4, 5, 6), armored=(3, 4, 6, 8), huscarl=(1, 2, 3, 4), skirm=(2, 2, 3, 4)),
    2: dict(name="eir_bh_wave2_name", levies=(1800, 2800, 4000, 6000), light=(3, 4, 5, 6), armored=(2, 3, 5, 7), huscarl=(1, 2, 3, 4), skirm=(2, 3, 3, 4)),
    3: dict(name="eir_bh_wave3_name", levies=(3000, 4500, 6500, 9000), light=(4, 5, 6, 8), armored=(5, 6, 8, 10), huscarl=(2, 3, 5, 6), skirm=(3, 3, 4, 5)),
}
TIER_LIMIT = ["eir_realm_size_trigger = { N = 20 }", "eir_realm_size_trigger = { N = 10 }", "eir_realm_size_trigger = { N = 4 }", None]


def spawn_block(w, t, indent="\t\t\t"):
    d = WAVES[w]
    # tier index: 0 = largest realm, 3 = smallest
    i = 3 - t
    pad = indent
    return (f"{pad}spawn_army = {{\n{pad}\tlevies = {d['levies'][i]}\n"
            f"{pad}\tmen_at_arms = {{\n{pad}\t\ttype = light_footmen\n{pad}\t\tstacks = {d['light'][i]}\n{pad}\t}}\n"
            f"{pad}\tmen_at_arms = {{\n{pad}\t\ttype = armored_footmen\n{pad}\t\tstacks = {d['armored'][i]}\n{pad}\t}}\n"
            f"{pad}\tmen_at_arms = {{\n{pad}\t\ttype = huscarl\n{pad}\t\tstacks = {d['huscarl'][i]}\n{pad}\t}}\n"
            f"{pad}\tmen_at_arms = {{\n{pad}\t\ttype = bowmen\n{pad}\t\tstacks = {d['skirm'][i]}\n{pad}\t}}\n"
            f"{pad}\tlocation = scope:eir_target_county.title_province\n{pad}\torigin = scope:eir_bh_lord.capital_province\n"
            f"{pad}\tinheritable = no\n{pad}\tuses_supply = no\n{pad}\tname = {d['name']}\n{pad}}}\n")


def landing(w):
    out = f"""# Wave {w} of the Black Host. Expects root = the defender, scope:eir_bh_lord and scope:eir_target_county.
eir_bh_landing_{w}_effect = {{
	save_scope_as = eir_defender
	if = {{
		limit = {{
			exists = scope:eir_bh_lord
			exists = scope:eir_target_county
			exists = scope:eir_target_county.holder
		}}
		set_variable = {{
			name = eir_bh_lord_var
			value = scope:eir_bh_lord
		}}
		set_variable = {{
			name = eir_bh_county_var
			value = scope:eir_target_county
		}}
		scope:eir_bh_lord = {{
			set_variable = {{
				name = eir_bh_raider
				value = {w}
			}}
			set_variable = {{
				name = eir_viking_target
				value = scope:eir_target_county
			}}
			add_character_modifier = {{
				modifier = eir_black_host_modifier
				years = 4
			}}
			add_pressed_claim = scope:eir_target_county
"""
    first = True
    for t in range(4):
        lim = TIER_LIMIT[t]
        kw = "if" if first else ("else_if" if lim else "else")
        first = False
        out += f"\t\t\t{kw} = {{\n"
        if lim:
            out += f"\t\t\t\tlimit = {{\n\t\t\t\t\tscope:eir_defender = {{ {lim} }}\n\t\t\t\t}}\n"
        out += spawn_block(w, t, "\t\t\t\t")
        out += "\t\t\t}\n"
    out += """			add_character_flag = temp_no_claim_war_cost
			start_war = {
				cb = claim_cb
				target = scope:eir_target_county.holder
				claimant = scope:eir_bh_lord
				target_title = scope:eir_target_county
			}
			remove_character_flag = temp_no_claim_war_cost
		}
	}
}

"""
    return out


EFFECTS = """##########################################################################
# Eire Reborn - Update 2 effects (generated by tools/gen_script_v8.py)
##########################################################################

# Picks the Black Host's warlord: a Norse AI ruler, the bigger the likelier. root = the defender.
# Saves scope:eir_bh_lord and scope:eir_target_county (a coastal county of the realm).
eir_bh_pick_effect = {
	random_ruler = {
		limit = {
			is_ai = yes
			is_ruler = yes
			highest_held_title_tier >= tier_county
			culture ?= { has_cultural_pillar = heritage_north_germanic }
			NOT = { has_truce = root }
			NOT = { this = root }
		}
		weight = {
			base = 1
			modifier = {
				add = 10
				highest_held_title_tier >= tier_duchy
			}
			modifier = {
				add = 20
				highest_held_title_tier >= tier_kingdom
			}
			modifier = {
				add = 10
				max_military_strength >= 3000
			}
		}
		save_scope_as = eir_bh_lord
	}
	if = {
		limit = {
			any_realm_county = { is_coastal_county = yes }
		}
		random_realm_county = {
			limit = { is_coastal_county = yes }
			save_scope_as = eir_target_county
		}
	}
	else = {
		capital_county ?= { save_scope_as = eir_target_county }
	}
}

""" + landing(1) + landing(2) + landing(3) + """# --------------------------------------------------------------------------------------------------
# The outcome of a Black Host wave, called in the defender's scope (the player, or the player when a vassal fought).
# --------------------------------------------------------------------------------------------------
eir_bh_wave_won_effect = {
	change_variable = {
		name = eir_bh_wins
		add = 1
	}
	trigger_event = eir.0420
}

eir_bh_wave_lost_effect = {
	change_variable = {
		name = eir_bh_losses
		add = 1
	}
	trigger_event = eir.0421
}

# --------------------------------------------------------------------------------------------------
# Lesser invasions. Expects root = the defender, scope:eir_inv_lord and scope:eir_target_county.
# KIND: 1 Briton, 2 Alban Gael, 3 Irish rival, 5 Hebridean Norse. LEVIES / STACKS tune the host.
# --------------------------------------------------------------------------------------------------
eir_inv_launch_effect = {
	if = {
		limit = {
			exists = scope:eir_inv_lord
			exists = scope:eir_target_county
			exists = scope:eir_target_county.holder
		}
		scope:eir_inv_lord = {
			set_variable = {
				name = eir_inv_kind
				value = $KIND$
			}
			set_variable = {
				name = eir_viking_target
				value = scope:eir_target_county
			}
			add_pressed_claim = scope:eir_target_county
			spawn_army = {
				levies = $LEVIES$
				men_at_arms = {
					type = light_footmen
					stacks = $STACKS$
				}
				men_at_arms = {
					type = armored_footmen
					stacks = $STACKS$
				}
				location = scope:eir_target_county.title_province
				origin = capital_province
				inheritable = no
				uses_supply = no
				name = $NAME$
			}
			add_character_flag = temp_no_claim_war_cost
			start_war = {
				cb = claim_cb
				target = scope:eir_target_county.holder
				claimant = scope:eir_inv_lord
				target_title = scope:eir_target_county
			}
			remove_character_flag = temp_no_claim_war_cost
		}
	}
}

# A Briton (Welsh, Cornish, Cumbrian or Breton) AI ruler and a coastal county. root = defender.
eir_pick_briton_invader_effect = {
	random_ruler = {
		limit = {
			is_ai = yes
			is_ruler = yes
			highest_held_title_tier >= tier_county
			culture ?= { has_cultural_pillar = heritage_brythonic }
			NOT = { has_truce = root }
			NOT = { this = root }
		}
		save_scope_as = eir_inv_lord
	}
	eir_pick_target_county_effect = yes
}

# An Alban Gael (Goidelic, not Irish) AI ruler.
eir_pick_alban_invader_effect = {
	random_ruler = {
		limit = {
			is_ai = yes
			is_ruler = yes
			highest_held_title_tier >= tier_county
			culture ?= { has_cultural_pillar = heritage_goidelic }
			NOT = { culture = culture:irish }
			NOT = { has_truce = root }
			NOT = { this = root }
		}
		save_scope_as = eir_inv_lord
	}
	eir_pick_target_county_effect = yes
}

# An independent Irish AI king who is not the defender.
eir_pick_rival_king_effect = {
	random_ruler = {
		limit = {
			is_ai = yes
			is_ruler = yes
			is_independent_ruler = yes
			highest_held_title_tier >= tier_county
			culture = culture:irish
			NOT = { has_truce = root }
			NOT = { this = root }
		}
		save_scope_as = eir_inv_lord
	}
	eir_pick_target_county_effect = yes
}

# A Norse-Gaelic or Norse AI ruler for the small Hebridean-style raids.
eir_pick_isles_raider_effect = {
	random_ruler = {
		limit = {
			is_ai = yes
			is_ruler = yes
			highest_held_title_tier >= tier_county
			highest_held_title_tier <= tier_duchy
			culture ?= { has_cultural_pillar = heritage_north_germanic }
			NOT = { has_truce = root }
			NOT = { this = root }
		}
		save_scope_as = eir_inv_lord
	}
	eir_pick_target_county_effect = yes
}

eir_pick_target_county_effect = {
	if = {
		limit = {
			any_realm_county = { is_coastal_county = yes }
		}
		random_realm_county = {
			limit = { is_coastal_county = yes }
			save_scope_as = eir_target_county
		}
	}
	else = {
		capital_county ?= { save_scope_as = eir_target_county }
	}
}

# --------------------------------------------------------------------------------------------------
# Conquest, culture and triumph helpers
# --------------------------------------------------------------------------------------------------

# Converts one county held by the realm that has a foreign culture (Britain or Norse) to the ruler's culture,
# remembering it in scope:eir_conv_county. Used by colonists, the Ostmen decision and triumphs.
eir_convert_one_county_effect = {
	random_sub_realm_county = {
		limit = { eir_foreign_conquest_county_trigger = yes }
		save_scope_as = eir_conv_county
		set_county_culture = root.culture
	}
}

# A triumph: every foreign-held county of the realm gets a short-lived triumph modifier, vassals are impressed,
# and the world notices.
eir_triumph_glory_effect = {
	every_sub_realm_county = {
		limit = { eir_foreign_conquest_county_trigger = yes }
		add_county_modifier = {
			modifier = eir_triumph_county_modifier
			years = 10
		}
	}
	eir_vassal_opinion_effect = { MODIFIER = eir_triumph_opinion OPINION = 8 }
}

# Burns the Norse grip on the realm: removes danegeld modifiers and the flag.
eir_end_danegeld_effect = {
	if = {
		limit = { has_character_modifier = eir_danegeld_modifier }
		remove_character_modifier = eir_danegeld_modifier
	}
	if = {
		limit = { has_character_flag = eir_paid_danegeld }
		remove_character_flag = eir_paid_danegeld
	}
}
"""

TRIGGERS = """##########################################################################
# Eire Reborn - Update 2 triggers (generated by tools/gen_script_v8.py)
##########################################################################

# County scope: a county the realm conquered or holds that is not of a Celtic culture:
# a foreign (non-Gaelic, non-Brythonic) county in Britain, or a Norse-culture county anywhere.
eir_foreign_conquest_county_trigger = {
	OR = {
		eir_foreign_britain_county_trigger = yes
		culture ?= { has_cultural_pillar = heritage_north_germanic }
	}
}

# Character scope: at least $N$ foreign-held counties in the realm.
eir_foreign_conquests_trigger = {
	any_sub_realm_county = {
		count >= $N$
		eir_foreign_conquest_county_trigger = yes
	}
}

# Character scope: the Black Host has landed and is not yet beaten.
eir_bh_active_trigger = {
	has_global_variable = eir_bh_started
	NOT = { has_global_variable = eir_bh_ended }
}

# Character scope: the player beat the Black Host.
eir_bh_beaten_trigger = {
	has_global_variable = eir_black_host_broken
}

# Character scope: a Norse-culture ruler holds a county in the realm or in de jure Ireland.
eir_norse_presence_trigger = {
	OR = {
		any_sub_realm_county = {
			culture ?= { has_cultural_pillar = heritage_north_germanic }
		}
		eir_norse_holds_irish_county_trigger = yes
	}
}

# Character scope: the realm holds a Norse-culture county of its own.
eir_holds_norse_county_trigger = {
	any_sub_realm_county = {
		culture ?= { has_cultural_pillar = heritage_north_germanic }
	}
}

# Character scope: at least $N$ counties in Britain held by the realm are of a Celtic culture (any origin).
eir_celtic_britain_counties_trigger = {
	any_sub_realm_county = {
		count >= $N$
		title_province ?= { geographical_region = world_europe_west_britannia }
		culture ?= {
			OR = {
				has_cultural_pillar = heritage_goidelic
				has_cultural_pillar = heritage_brythonic
			}
		}
	}
}

# Early game: a ruler with few counties (shows the chieftain-level stories).
eir_small_realm_trigger = {
	NOT = { eir_realm_size_trigger = { N = 8 } }
}
"""

TRIGGERS += """
# Character scope: the realm can found the Kingdom of the Island of the Mighty.
eir_can_create_island_kingdom_trigger = {
	highest_held_title_tier >= tier_kingdom
	has_global_variable = eir_done_union
	eir_celtic_britain_counties_trigger = { N = 6 }
	any_sub_realm_county = { this = title:c_isle_of_man }
}

# Character scope: the realm holds a coastal county in Great Britain.
eir_holds_british_port_trigger = {
	any_sub_realm_county = {
		is_coastal_county = yes
		OR = {
			kingdom = title:k_england
			kingdom = title:k_scotland
			kingdom = title:k_wales
		}
	}
}

# Character scope: an independent Gaelic ruler lives within reach.
eir_has_gael_neighbour_trigger = {
	any_ruler = {
		is_ai = yes
		is_ruler = yes
		culture ?= { has_cultural_pillar = heritage_goidelic }
		NOT = { this = root }
		NOT = { is_vassal_of = root }
	}
}
"""

EFFECTS += """
# The colony stored in var:eir_colony_county takes the ruler's culture.
eir_colony_convert_effect = {
	if = {
		limit = { has_variable = eir_colony_county }
		var:eir_colony_county ?= {
			set_county_culture = root.culture
			add_county_modifier = {
				modifier = eir_hedge_schools_modifier
				years = 15
			}
		}
		remove_variable = eir_colony_county
	}
}
"""

ONACTIONS = """##########################################################################
# Eire Reborn - Update 2 on_actions (additive to the vanilla and v0.1 ones)
##########################################################################

eir_war_won_attacker_v8 = {
	effect = {
		scope:attacker = {
			if = {
				limit = { has_variable = eir_bh_raider }
				scope:attacker = { save_scope_as = eir_bh_lord }
				scope:defender = {
					if = {
						limit = { is_ai = no }
						eir_bh_wave_lost_effect = yes
					}
					else_if = {
						limit = {
							exists = liege
							liege = { is_ai = no }
						}
						liege = { eir_bh_wave_lost_effect = yes }
					}
				}
				remove_variable = eir_bh_raider
				remove_variable = eir_viking_target
			}
			else_if = {
				limit = { has_variable = eir_inv_kind }
				scope:attacker = { save_scope_as = eir_inv_lord }
				scope:attacker.var:eir_viking_target ?= { save_scope_as = eir_target_county }
				scope:defender = {
					if = {
						limit = {
							is_ai = yes
							exists = liege
							liege = { is_ai = no }
						}
						liege = { save_scope_as = eir_inv_player }
					}
					else_if = {
						limit = { is_ai = no }
						save_scope_as = eir_inv_player
					}
				}
				if = {
					limit = { exists = scope:eir_inv_player }
					scope:eir_inv_player = {
						if = {
							limit = { scope:eir_inv_lord.var:eir_inv_kind = 1 }
							trigger_event = eir.0423
						}
						else_if = {
							limit = { scope:eir_inv_lord.var:eir_inv_kind = 2 }
							trigger_event = eir.0425
						}
						else_if = {
							limit = { scope:eir_inv_lord.var:eir_inv_kind = 3 }
							trigger_event = eir.0427
						}
						else = {
							trigger_event = eir.0429
						}
					}
				}
				remove_variable = eir_inv_kind
				remove_variable = eir_viking_target
			}
		}
	}
}

eir_war_won_defender_v8 = {
	effect = {
		scope:attacker = {
			if = {
				limit = { has_variable = eir_bh_raider }
				scope:attacker = { save_scope_as = eir_bh_lord }
				scope:defender = {
					if = {
						limit = { is_ai = no }
						eir_bh_wave_won_effect = yes
					}
					else_if = {
						limit = {
							exists = liege
							liege = { is_ai = no }
						}
						liege = { eir_bh_wave_won_effect = yes }
					}
				}
				remove_variable = eir_bh_raider
				remove_variable = eir_viking_target
			}
			else_if = {
				limit = { has_variable = eir_inv_kind }
				scope:attacker = { save_scope_as = eir_inv_lord }
				scope:attacker.var:eir_viking_target ?= { save_scope_as = eir_target_county }
				scope:defender = {
					if = {
						limit = {
							is_ai = yes
							exists = liege
							liege = { is_ai = no }
						}
						liege = { save_scope_as = eir_inv_player }
					}
					else_if = {
						limit = { is_ai = no }
						save_scope_as = eir_inv_player
					}
				}
				if = {
					limit = { exists = scope:eir_inv_player }
					scope:eir_inv_player = {
						if = {
							limit = { scope:eir_inv_lord.var:eir_inv_kind = 1 }
							trigger_event = eir.0422
						}
						else_if = {
							limit = { scope:eir_inv_lord.var:eir_inv_kind = 2 }
							trigger_event = eir.0424
						}
						else_if = {
							limit = { scope:eir_inv_lord.var:eir_inv_kind = 3 }
							trigger_event = eir.0426
						}
						else = {
							trigger_event = eir.0428
						}
					}
				}
				remove_variable = eir_inv_kind
				remove_variable = eir_viking_target
			}
		}
	}
}

# The Black Host: a 12 percent chance a year from 868, certain from 880, once per game.
eir_blackhost_pulse = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		current_year >= 868
		current_year < 880
		NOT = { has_global_variable = eir_bh_started }
		eir_has_coast_trigger = yes
	}
	random_events = {
		chance_to_happen = 12
		1 = eir.0400
	}
}

eir_blackhost_forced_pulse = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		current_year >= 880
		NOT = { has_global_variable = eir_bh_started }
		eir_has_coast_trigger = yes
	}
	first_valid = {
		eir.0400
	}
}

# Lesser invasions: Britons, Albans, Irish rivals and Hebridean raiders. Rarer than the flavor pulse, bigger than a raid.
eir_invasion_pulse_v8 = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		current_year >= 870
		is_at_war = no
		NOT = { has_character_flag = eir_invasion_cd }
		eir_has_coast_trigger = yes
	}
	random_events = {
		chance_to_happen = 14
		10 = 0
		4 = eir.0410
		4 = eir.0411
		4 = eir.0412
		3 = eir.0413
	}
}

eir_norse_pulse_v8 = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		NOT = { has_character_flag = eir_flavor_cd }
		eir_viking_age_trigger = yes
		eir_has_coast_trigger = yes
	}
	random_events = {
		chance_to_happen = 30
		30 = 0
		5 = eir.0440
		5 = eir.0441
		5 = eir.0442
		5 = eir.0443
		5 = eir.0444
		5 = eir.0445
		5 = eir.0446
		5 = eir.0447
		5 = eir.0448
		5 = eir.0449
		5 = eir.0450
		5 = eir.0451
		5 = eir.0452
		5 = eir.0453
	}
}

eir_gael_pulse_v8 = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		NOT = { has_character_flag = eir_flavor_cd }
		eir_realm_size_trigger = { N = 2 }
	}
	random_events = {
		chance_to_happen = 30
		30 = 0
		5 = eir.0456
		5 = eir.0457
		5 = eir.0458
		5 = eir.0459
		5 = eir.0460
		5 = eir.0461
		5 = eir.0462
		5 = eir.0463
		5 = eir.0464
		5 = eir.0465
		5 = eir.0466
		5 = eir.0467
		5 = eir.0468
		5 = eir.0469
		5 = eir.0470
		5 = eir.0471
	}
}

eir_britain_pulse_v8 = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		NOT = { has_character_flag = eir_flavor_cd }
		OR = {
			eir_has_foreign_britain_counties_trigger = yes
			eir_has_celtic_britain_counties_trigger = yes
		}
	}
	random_events = {
		chance_to_happen = 35
		30 = 0
		5 = eir.0480
		5 = eir.0481
		5 = eir.0482
		5 = eir.0483
		5 = eir.0484
		5 = eir.0485
		5 = eir.0486
		5 = eir.0487
		5 = eir.0488
		5 = eir.0489
		5 = eir.0490
		5 = eir.0491
		5 = eir.0492
		5 = eir.0493
		5 = eir.0494
		5 = eir.0495
		5 = eir.0496
		5 = eir.0497
		5 = eir.0498
		5 = eir.0499
		5 = eir.0516
		5 = eir.0517
		5 = eir.0518
		5 = eir.0519
		5 = eir.0520
		5 = eir.0521
		5 = eir.0522
		5 = eir.0523
	}
}

# Early game: chieftain-level stories for rulers of a few counties. 1 chance in 3 a year, 3 years apart at most.
eir_early_pulse = {
	trigger = {
		eir_is_gael_ruler_trigger = yes
		is_ai = no
		eir_small_realm_trigger = yes
		NOT = { has_character_flag = eir_early_cd }
	}
	random_events = {
		chance_to_happen = 40
		30 = 0
		4 = eir.0530
		4 = eir.0531
		4 = eir.0532
		4 = eir.0533
		4 = eir.0534
		4 = eir.0535
		4 = eir.0536
		4 = eir.0537
		4 = eir.0538
		4 = eir.0539
		3 = eir.0540
		3 = eir.0541
		3 = eir.0542
		3 = eir.0543
	}
}
"""


def build():
    write("common/scripted_effects/eir_effects_v8.txt", EFFECTS)
    write("common/scripted_triggers/eir_triggers3.txt", TRIGGERS)
    write("common/on_action/eir_on_actions_v8.txt", ONACTIONS)
    print("script v8 written")


if __name__ == "__main__":
    build()
