"""Writes docs/DECISIONS.md: a plain-language list of every decision, its requirements, cost and rewards."""
import io, os, re
from eir_lib import ROOT
import gen_decisions as g
import dec_v2  # noqa: F401
import dec_v7  # noqa: F401


def clean(valid):
    lines = [l.strip() for l in valid.split("\n") if l.strip() and l.strip() not in ("}", "{")]
    keep = []
    for l in lines:
        if l.startswith(("OR = {", "NOT = {", "any_", "count >=")) or "=" in l:
            keep.append(l)
    return "; ".join(keep)


def build():
    out = ["# Eire Reborn - decisions, requirements, costs and rewards\n\nGenerated by tools/gen_docs.py. Stage triggers: see README.\n\n"]
    out.append("| Decision | Cost | Requirements (is_valid) | What it does |\n|---|---|---|---|\n")
    for d in g.DEC:
        cost = d["cost"].replace("\n", ", ") or "free"
        req = clean(d["valid"]).replace("|", "/")
        out.append("| **%s**%s | %s | %s | %s |\n" % (d["name"], " (major)" if d["major"] else "", cost, req, d["tip"].replace("|", "/")))
    p = os.path.join(ROOT, "docs", "DECISIONS.md")
    io.open(p, "w", encoding="utf-8", newline="").write("".join(out))
    print("docs written:", len(g.DEC), "decisions")


if __name__ == "__main__":
    build()
