"""Generates common/decisions/eir_decisions.txt and its localization.

Unlock progress is stored in GLOBAL variables (eir_done_*, eir_unlock_*) so it survives from ruler to ruler.
Negative-effect decisions are paired with a remedy decision (the 40% rule in the design guide).
"""
from eir_lib import *

IRISH = "eir_is_irish_ruler_trigger = yes"
GAEL = "eir_is_gael_ruler_trigger = yes"

DEC = []


def D(key, name, desc, tip, shown, effect, valid="", cost="", cd=3650, major=False, pic="decision_misc"):
    DEC.append(dict(key=key, name=name, desc=desc, tip=tip, shown=shown, effect=effect, valid=valid,
                    cost=cost, cd=cd, major=major, pic=pic))


def ind(text, tabs):
    pad = "\t" * tabs
    return "".join(pad + line + "\n" if line.strip() else "\n" for line in text.strip("\n").split("\n"))


def build():
    import dec_v2  # noqa: F401  (registers every decision)
    L = Loc("eir_decisions_l_english.yml")
    out = ["# Eire Reborn - decisions. Generated by tools/gen_decisions.py\n\n"]
    for d in DEC:
        key = d["key"]
        out.append("%s = {\n" % key)
        out.append('\tpicture = {\n\t\treference = "gfx/interface/illustrations/decisions/%s.dds"\n\t}\n' % d["pic"])
        if d["major"]:
            out.append("\tdecision_group_type = major\n")
        out.append("\tai_check_interval = 0\n\tsort_order = 40\n")
        out.append("\tdesc = %s_desc\n\tselection_tooltip = %s_tooltip\n\tconfirm_text = %s_confirm\n\n" % (key, key, key))
        out.append("\tcooldown = { days = %d }\n\n" % d["cd"])
        out.append("\tis_shown = {\n%s\t}\n\n" % ind(d["shown"], 2))
        if d["valid"]:
            out.append("\tis_valid = {\n%s\t}\n\n" % ind(d["valid"], 2))
        out.append("\tis_valid_showing_failures_only = {\n\t\tis_available_adult = yes\n\t\tis_imprisoned = no\n\t}\n\n")
        if d["cost"]:
            out.append("\tcost = {\n%s\t}\n\n" % ind(d["cost"], 2))
        out.append("\teffect = {\n%s\t}\n\n" % ind(d["effect"], 2))
        out.append("\tai_will_do = {\n\t\tbase = 0\n\t}\n}\n\n")
        L.add(key, d["name"])
        L.add(key + "_desc", d["desc"])
        L.add(key + "_tooltip", d["tip"])
        L.add(key + "_confirm", d["name"])
    write("common/decisions/eir_decisions.txt", "".join(out))
    L.write()
    print("decisions:", len(DEC))


if __name__ == "__main__":
    build()
