"""Generates events/eir_events_*.txt and localization from the data modules ev_*.py.

An event is described with E(...). Options are Opt(...). Everything the text needs is generated together
so keys cannot go missing. Run tools/validate.py afterwards.
"""
import importlib
from eir_lib import *
from evdsl import Opt, Event, E, lab, LABELS

EVENT_FILES = {}   # filename -> list of events


def ind(text, tabs):
    pad = "\t" * tabs
    return "".join(pad + line + "\n" if line.strip() else "\n" for line in text.strip("\n").split("\n"))


def render(ev, L):
    key = "eir.%04d" % ev.num
    out = ["%s = {\n" % key]
    if ev.hidden:
        out.append("\ttype = character_event\n\thidden = yes\n")
    else:
        out.append("\ttype = %s\n\ttitle = %s.t\n\tdesc = %s.desc\n\ttheme = %s\n" % (ev.ev_type, key, key, ev.theme))
    if ev.cooldown:
        out.append("\tcooldown = { years = %d }\n" % ev.cooldown)
    if ev.portraits and not ev.hidden:
        out.append(ind(ev.portraits, 1))
    if ev.trigger:
        out.append("\n\ttrigger = {\n%s\t}\n" % ind(ev.trigger, 2))
    if ev.immediate:
        out.append("\n\timmediate = {\n%s\t}\n" % ind(ev.immediate, 2))
    if not ev.hidden:
        L.add(key + ".t", ev.title)
        L.add(key + ".desc", "#bold %s#!\n\n%s" % (ev.summary, ev.body) if ev.body else "#bold %s#!" % ev.summary)
        for i, o in enumerate(ev.options):
            letter = "abcdefghij"[i]
            out.append("\n\toption = {\n\t\tname = %s.%s\n" % (key, letter))
            if o.trigger:
                out.append("\t\ttrigger = {\n%s\t\t}\n" % ind(o.trigger, 3))
            if o.stress:
                out.append("\t\tstress_impact = {\n%s\t\t}\n" % ind(o.stress.replace(" ", "\n", 0), 3))
            if o.effect:
                out.append(ind(o.effect, 2))
            if o.ai is not None:
                out.append("\t\tai_chance = { base = %d }\n" % o.ai)
            out.append("\t}\n")
            L.add("%s.%s" % (key, letter), o.text)
    out.append("}\n\n")
    return "".join(out)


def load_groups():
    groups = {}
    for mod in ("ev_tanistry", "ev_vikings", "ev_foreign", "ev_flavor", "ev_church_court", "ev_history", "ev_celtic", "ev_rewards", "ev_era867", "ev_resist", "ev_chains", "ev_extra", "ev_v5", "ev_v6"):
        try:
            m = importlib.import_module(mod)
        except ModuleNotFoundError as e:
            if e.name == mod:
                continue
            raise
        groups[mod] = m.EVENTS
    # risky extra options for events that had no downside (defined in ev_v6.PATCH)
    try:
        import ev_v6
        for evs in groups.values():
            for ev in evs:
                for opt in ev_v6.PATCH.get(ev.num, []):
                    if opt not in ev.options:
                        ev.options.append(opt)
    except ModuleNotFoundError:
        pass
    return groups


def build():
    groups = load_groups()
    total = 0
    seen = set()
    for i, (name, events) in enumerate(groups.items(), start=1):
        L = Loc("eir_%s_l_english.yml" % name)
        out = ["namespace = eir\n\n# Eire Reborn - %s. Generated by tools/gen_events.py\n\n" % name]
        for ev in events:
            if ev.num in seen:
                raise SystemExit("duplicate event number %d" % ev.num)
            seen.add(ev.num)
            out.append(render(ev, L))
        write("events/eir_%s.txt" % name, "".join(out))
        L.write()
        total += len(events)
    LL = Loc("eir_event_labels_l_english.yml")
    for k in sorted(LABELS):
        LL.add(k, LABELS[k])
    LL.write()
    print("events:", total, "in", len(groups), "files;", len(LABELS), "outcome labels")


if __name__ == "__main__":
    build()
